### ISSUE TITLE
formly-js/angular-formly has been archived

### ISSUE THREAD

**Issue by mquinson** [up-for-grabs/up-for-grabs.net#1015]
Hello,

I was lurking in the list and then I clicked on https://github.com/formly-js/angular-formly/labels/up-for-grabs 

This shows a tiny banner saying " This repository has been archived by the owner. It is now read-only". It sounds like it should be removed from your list, then. Newcomers may be disappointed if they realize too late that the project is not any more welcoming contributions.

Also, I was wondering whether there is a way to automatically detect when projects get archived, to automatically cure the list that you provide.

Thanks for this great initiative, I'll soon add some of my project to make my "beginner friendly" issues more visible.

**Comment by ritwik12** [comment]
@mquinson Thanks for the info, appreciate your concern.

**Comment by ritwik12** [comment]
@mquinson Your idea of automatically detecting archived projects is great and will be of great use. I am creating an issue for that so that it could be implemented.

**Comment by ritwik12** [comment]
@mquinson merged
