### ISSUE TITLE
Permission: Add Microsoft OSS repos? 

### ISSUE THREAD

**Issue by SeanKilleen** [up-for-grabs/up-for-grabs.net#1028]
Hi all,

I got curious after [Microsoft jumped into Hacktoberfest](https://open.microsoft.com/2018/09/18/hacktoberfest-2018-microsoft/). I wondered, since it has [2,000+ repos on GitHub](https://opensource.microsoft.com/), do they have tags that would be compatible with up-for-grabs?

I wrote a quick console app with octokit to parse it out and it looks like 1,914 repos have a `help wanted` tag or `good first issue` tag (some have both!).

I've automated the process to extract them, and I think I can automate the process to create them in the up-for-grabs repo, but then I realized with great power comes great responsibility. :)

So before I got the rest of the way and offer this PR, I wanted to ask: would this be hugely disruptive to the repo/site? Is there any criteria you'd like me to determine whether to submit a given repo? (number of stars, maybe?)

Checking in here before I go further on it. If I don't hear back, I'll likely submit the repos with the top x% of stars.

**Comment by SeanKilleen** [comment]
At this point, I have a list of:

* All the MS public repos
* Their star counts
* The labels that fit with "up for grabs" style label names
* The count of issues in each repo associated with that label

I know some of the heavy hitters such as TypeScript and MSBuild are already listed, but I'm hoping I can help list others (and OSS this little project myself, because why not?)

**Comment by ritwik12** [comment]
@SeanKilleen Hey, thanks for this great idea. This is really good and will be of good use to beginners. The only thing that concerns me is the huge number of repos which I think will be too much. Having too much creates confusion for others to choose and work too.

**Comment by ritwik12** [comment]
Ping @dahlbyk and @shiftkey

**Comment by dahlbyk** [comment]
Just my personal opinion here, but if a project hasn't taken the explicit step of submitting themselves here I am not super comfortable assuming they're actually looking for help in the way we mean it. In theory that's what "help wanted" says, but it's also an easy default provided by GitHub that often means "won't fix".

Perhaps we could add links to the effect of…

> Not finding what you're looking for here? Try searching GitHub for "up-for-grabs", "help wanted" or "good first issue".

With the label names linked. We could even include current filter tags in the search somehow.

**Comment by SeanKilleen** [comment]
@dahlbyk totally fair. I envisioned a personal curation prior to submission anyway. If I was to find the list of MS repos with those tags that looked to be in line with up-for-grabs and submit them here, would that be OK in your opinion? That way we're not adding a ton and a human has at least looked at it.

**Comment by dahlbyk** [comment]
@SeanKilleen that sounds great. Thanks! If you can identify a person on the projects who tends to be assigning their up-for-grabs–ish, it seems reasonable to tag them when you submit here.

**Comment by ritwik12** [comment]
@SeanKilleen @dahlbyk Agreed.

**Comment by shiftkey** [comment]
I'm also 👍 to some sort of curation here rather than getting them added in bulk - projects that are active and visible, projects with open issues more suited to new OSS peeps, projects with maintainers that are great at encouraging new contributors, that sort of thing...

**Comment by SeanKilleen** [comment]
Sounds good! I'll run the curation by hand and will list criteria for each in the description of the PR where I add them. I'll close this issue via that PR, or feel free to close this now if you need to for housekeeping.

**Comment by shiftkey** [comment]
@SeanKilleen I'm going to close this out for housekeeping reasons, but I'd still love to see curated and active project from Microsoft that align with the goals of Up for Grabs listed here.

I worry that adding all 1900+ repositories would dwarf the existing projects listed on the site, but starting with a PR for a small sample would be a good starting point to get a feel for what this looks like.

**Comment by SeanKilleen** [comment]
No worries! This did fall off my radar a little bit. 

I'll work to OSS the little utility I created that surfaces up for grabs projects and then use the results to reopen this.

It will:

* Crawl an org's repos
* Look for whether those tags exist
* If they do, look for how many issues have had those tags
* Look at # stars / forks / watchers
* Spits out applicable info
* Note the Latest commit to default branch

**Comment by SeanKilleen** [comment]
FYI, the very early days of this tool are now up at https://github.com/SeanKilleen/up-for-grabber.

I'll intend to iterate on it a bunch. For now it only gets as far as seeing how many issues with up-for-grabs style labels exist across an org, and it takes a while and the only way to really spelunk the output is with the logging to Seq locally. 

More to come.

**Comment by ritwik12** [comment]
@SeanKilleen That looks great, I have checked the repo. Waiting to see lots of PR from you in the future :P
