### ISSUE TITLE
Multiple filter at a time

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1070]
Right now we have three filters - `Filter by name: `, `Filter by label: ` and `Filter by tags: `
And we are able to use only one Filter at a time.
I think it will be really good to have `Filter by label` and `Filter by tags` to be used simultanously.

**Comment by ritwik12** [comment]
@Isfaaq  I'm not able to assign this to you. But you may work on this as it is open.

**Comment by Zarad1993** [comment]
@ritwik12 - Is this being worked on now? I think I have something nice in mind for this.

**Comment by juliankrieger** [comment]
@Zarad1993 not that I know of

**Comment by Zarad1993** [comment]
@juliankrieger Ok I'm going to start on this.

**Comment by ritwik12** [comment]
@Zarad1993 Sure, go on with this please.
