### ISSUE TITLE
Jekyll fails at getting GitHub Metadata

### ISSUE THREAD

**Issue by juliankrieger** [up-for-grabs/up-for-grabs.net#1093]
Travis delivers the following error code at building recent builds. This is most likely due to https://github.com/github/pages-gem/issues/399

Error code:
`GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: GET https://api.github.com/repos/up-for-grabs/up-for-grabs.net/pages: 403 - API rate limit exceeded for 35.192.85.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting`

Suggestion:
Adding  `github: [metadata]` to _config.yml fixed the problem on my side. It's also the workaround in the aforementioned github issues post.

**Comment by juliankrieger** [comment]
@ritwik12 I implemented this a while ago in #1100. I'd be happy if you were able to test the issue on your side, too

**Comment by ritwik12** [comment]
@juliankrieger Yes I saw. Sorry to keep you waiting. I was waiting for @shiftkey to review it.

**Comment by shiftkey** [comment]
I think #1100 addresses this, but let me know if you notice any future builds with the issue
