### ISSUE TITLE
Beyond .NET

### ISSUE THREAD

**Issue by dahlbyk** [up-for-grabs/up-for-grabs.net#11]
I had originally registered this thinking it would only be useful to the .NET community, but @jrusbatch rightly points out that all open source projects could benefit from making it easier for newbies to become good contributors (i.e. don't just show up and Resharper All The Things™).

So while we build this site out, let's find other projects that have a label to encourage new contributors (or invite projects we like to do so).

**Comment by jrusbatch** [comment]
:+1:

**Comment by nulltoken** [comment]
Proposal for a little C project with a welcoming tribe of contributors sits here: https://github.com/dahlbyk/up-for-grabs.net/pull/135

**Comment by ethomson** [comment]
:+1:

**Comment by jrusbatch** [comment]
This project has grown quite a bit since this issue was opened. I'm going to go ahead and mark this as complete.
