### ISSUE TITLE
Alphabetical order in Filters

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1106]
Filter by name was implemented in #1092 and fixed in #1104. It will be good to have the same for "Filter by label" and "Filter by tags"

**Comment by zeyadetman** [comment]
I fixed it in PR: [#1107](https://github.com/up-for-grabs/up-for-grabs.net/pull/1107)

**Comment by ritwik12** [comment]
@zeyadetman #1107 is not working properly. So, this issue is still open.

**Comment by zeyadetman** [comment]
What's the error? it works well local.

**Comment by ritwik12** [comment]
@ritwik12 No data is shown after applying filter.

**Comment by juliankrieger** [comment]
@ritwik12 , I have implemented this with the fix in #1111 , sorry for missing the bug in the first place

**Comment by juliankrieger** [comment]
You can preview it here ![alt text](https://raw.githubusercontent.com/juliankrieger/up-for-grabs.net/pictures/images/Screenshot_20181212_190859.png "Example 1")

and here

![alt text](https://raw.githubusercontent.com/juliankrieger/up-for-grabs.net/pictures/images/Screenshot_20181212_191049.png "Example 2")

**Comment by juliankrieger** [comment]
It also works with multiple labels, as you can see here
 ![alt text](https://raw.githubusercontent.com/juliankrieger/up-for-grabs.net/pictures/images/Screenshot_20181212_192012.png "Example 3")

**Comment by ritwik12** [comment]
@juliankrieger Looks good

**Comment by ritwik12** [comment]
@juliankrieger Filter by tags is not Alphabetical yet, right?

**Comment by juliankrieger** [comment]
@ritwik12 no, I added it right now
