### ISSUE TITLE
Filters ordering is case sensitive

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1109]
I noticed that the current "Filter by name:" is case sensitive and is ordering names Alphabetically but is also giving priority to Upper case.

**Comment by Zarad1993** [comment]
I'll take this one.

**Comment by ritwik12** [comment]
@Zarad1993 I guess we can assign only the collaborators of the repo and not to contributors. I am not able to assign it to you.

**Comment by ritwik12** [comment]
@shiftkey Please check if you can assign other people which don't have right access to this repo.
