### ISSUE TITLE
Clicking on a "popular" tag does not add a filter by that tag

### ISSUE THREAD

**Issue by charstarstar** [up-for-grabs/up-for-grabs.net#1116]
Clicking on a popular tag does not update the project listing to filter by that tag and the console shows a 404 after doing so. My guess is that this is due to the fact that the URL linked to for "popular" tags vs. selecting the tag manually through "Filter by tags" are different. 

The a href for python's "popular" tag is: 

> #/tags/python

The a href for python if clicked on in the "Filter by tags:" box is:

> #/filters/?tags=python

Proof of 404: 
<img width="482" alt="404s" src="https://user-images.githubusercontent.com/38056186/50034520-18cab700-ffb2-11e8-85ab-cd58ca9475ed.png">

Demonstrations:
Nonfunctional "popular" (The first three projects do not include python but do not disappear)
![popularstart](https://user-images.githubusercontent.com/38056186/50034772-45330300-ffb3-11e8-8c52-c64c943979ee.gif)

Functional "Filter by tags": (Projects that do not include python, like smallest dotnet, properly disappear) 

![filterbytags](https://user-images.githubusercontent.com/38056186/50034638-b920db80-ffb2-11e8-9d03-ace33219cbb1.gif)

I'm new to making public contributions to GitHub (this is my first one!) and I'd love feedback on my contributions like this issue report, especially if it's critical as I'm trying to improve. Thanks for reading! Hoping to confirm this is an issue before I try experimenting with fixing it!

**Comment by ritwik12** [comment]
@charstarstar Yes, it is an issue. Good work. Appreciate that. Also, a very good explanation.

**Comment by ritwik12** [comment]
@charstarstar Do you want to take this issue and work on it?

**Comment by ritwik12** [comment]
@charstarstar If you want to fix this, Have a look [here](https://github.com/up-for-grabs/up-for-grabs.net/blob/3d896714fda54d6a877c34843b48ce7da635c593/_includes/scripts.html#L26)

**Comment by ritwik12** [comment]
@charstarstar As you are new, so if you need any help like how to make contributions. Feel free to ping me.

**Comment by charstarstar** [comment]
@ritwik12 I have a pretty good idea of the exact, one-line change to be made if we're not nesting popular tags (i.e. clicking 'python' then 'c++' yields only c++ results as opposed to projects with either)

But I've failed to get it working locally, hence making the issue as I'm loath to edit anything without having tested the change first. I see the website as relatively basic HTML (see below) because some requests don't go through:

> GET https://github.com/pages/up-for-grabs/up-for-grabs.net/javascripts/main.js net::ERR_ABORTED 404 (Not Found)

Actual script (not raw) seems to be at

> https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/javascripts/main.js

I've probably screwed up the local setup somehow...but I am curious why {{site.github.url}} doesn't include raw.githubusercontent.com? If you have advice that'd be great as I'd like to tinker, but no worries if not -- setup is always the hardest part of the process for me!

> <img width="934" alt="screen shot 2018-12-15 at 11 39 08 pm" src="https://user-images.githubusercontent.com/38056186/50051213-012f2380-00c3-11e9-9350-72fb9913f7e4.png">

**Comment by juliankrieger** [comment]
@charstarstar try adding the following to your _config.yml

`github: [metadata]`

Also, try leaving out the 'watch' flag when running jekyll, as that's been known to cause some issues.

You can also try rebuilding and then running by `bundle exec jekyll serve`

**Comment by juliankrieger** [comment]
@ritwik12 I've tried to fix it with the following jQuery call, however I can't seem to get it to work..

```
projectsPanel.find("ul.popular-tags").each(function(i, elem){
            $(elem).on("click", function(){
                loation.href = updateQueryStringParameter(getFilterUrl(), 'tags', encodeURIComponent(($(this).val() || ""))); 
            })
        });
```

**Comment by juliankrieger** [comment]
When I log "elem" with console.log, it's just the unordered list itself.

**Comment by charstarstar** [comment]
If you want only the children perhaps something like:

```
$.each(projectsPanel.find("ul.popular-tags")[0].children, function(i, elem) { 
      $(elem).on("click", function() {
        //make element into the language only - e.g. strip from elem.innerHTML using regex like below, but there's almost certainly a better way
        language_regex = /(?:<a href ?=\".*\"> ?(.*?) ?<\/a>.*)/
        language = elem.innerHTML.match(language_regex)[0];
        //push element into tags: it may be undefined, in which case define it 
        if (tags) {
          tags.push(language);
        } else {
          tags = [language];
        }
        location.href = updateQueryStringParameter(getFilterUrl(), 'tags', encodeURIComponent((language || ""))); 
      })
});
```

There's probably a cleaner way of doing this though. Also probably want to change the a href in scripts.html as well (If you don't care about nesting etc. you could just update that to include filter?=<%-encodeURIComponent(tag)%> -- see below) because right now it just routes there anyway so it won't work beyond the first time. 

Changing scripts.html (29) to below mostly resolves the issue, but doesn't allow for nesting of tags via clicking on multiple 'popular' tags in a row (though you can additional tags manually). Also, if you remove the popular tag the URL doesn't remove the "/filters/?tags=" but that's how the site currently works for manual additions as well so perhaps that's not a problem. 

`<li><a href="#/filters?tags=<%-encodeURIComponent(entry.name)%>"><%-entry.name%></a> (<%-entry.frequency%>)</li>`

Do we care about nesting popular tags (i.e. from popular clicking "python" then "C++" gives results for both and not just C++) or not? IMO no, so I'd just make the one line change?
