### ISSUE TITLE
Add a scroll to top button

### ISSUE THREAD

**Issue by richa208** [up-for-grabs/up-for-grabs.net#1131]
Currently user has to scroll all the way to the top again.
Adding a button for such purpose would aid users.

**Comment by ritwik12** [comment]
@richa208 Button to scroll or you meant pagination?

**Comment by richa208** [comment]
@ritwik12 I referred to the button in this issue, but adding the pagination feature would also be nice.

**Comment by ritwik12** [comment]
@richa208 Pagination is already opened in #303  and #665 and is waiting for suitable PR. Whereas I think button will also be a good feature.
