### ISSUE TITLE
Suggestion: Can we order via for 'latest commits date' 

### ISSUE THREAD

**Issue by AllanOcelot** [up-for-grabs/up-for-grabs.net#1140]
There are alot of projects on the site that are no longer maintained / have been abandoned by their owner.

It would be great if we could sort based on last commit time.

**Comment by ritwik12** [comment]
@AllanOcelot  Well, that will be good. Let's have it in the way of `most active` repos or `recently updated`

**Comment by ritwik12** [comment]
Closing this wrt #1142
