### ISSUE TITLE
[Styling] Add styling to 'Tags'

### ISSUE THREAD

**Issue by AllanOcelot** [up-for-grabs/up-for-grabs.net#1160]
At the moment we display 'Tags' as simple text links - of inconsistent sizes. 

We should aim to have tags consistent, I have in mind something like github labels - a simple rectangle with rounded corners, a background colour and an easy to read text colour.

I'll experiment with this myself, but raising it as an issue incase anyone else would like to attempt with an easy to implement feature.

**Comment by ritwik12** [comment]
@AllanOcelot Great

**Comment by User5842** [comment]
I've noticed that the popular tags also do not have any `cursor: pointer` declaration attached to their stylings. Other `a` tags on the page do have the style so it could be a good idea to add them here as well.

**Comment by subhromajumder** [comment]
Hello, is this issue still open? I would like to work on it.

**Comment by ritwik12** [comment]
@subhromajumder It is open, please go ahead!!

**Comment by subhromajumder** [comment]
Okay!

**Comment by subhromajumder** [comment]
I am making changes to the stylesheet but it is not showing up on the local (cloned) website. Why is that happening? I am sorry, this might be a stupid question, I am a first timer.

**Comment by dkbearsong** [comment]
Is this issue still open? If so I'd like to take a crack at it.

**Comment by priyanks25coder** [comment]
Is this issue still open? Wanted to work on it so..

**Comment by maryanamorato** [comment]
could you assign to me?

**Comment by Potato-29** [comment]
is this still open?

**Comment by ritwik12** [comment]
Yep this is still open

**Comment by JiGzSaw01** [comment]
Hi! can i try to work on it?

**Comment by ritwik12** [comment]
@JiGzSaw01 Sure

**Comment by cweave** [comment]
Here's a sample of what I did:

Light mode with python in an active state:
![image](https://user-images.githubusercontent.com/16121690/194455726-d64651b9-c8f5-4b5f-8aef-2f74efcef440.png)

Dark mode with python in an active state:
![image](https://user-images.githubusercontent.com/16121690/194455887-08f0b514-a12a-4fd3-a403-1f7374cad97a.png)

I did the changes via code locally, so if y'all like it, its not much to make a PR or implement changes :)

**Comment by Sam10-debug** [comment]
id like to work on this, can this be assigned to me please

**Comment by Tech-frank** [comment]
Can I join in this? I'm a first timer so...

**Comment by AtharvKasar04** [comment]
Hello, Is the issue still open to fix? I can add styling to the tags that would definitely improve the looks of those.
