### ISSUE TITLE
Add Docs for JS modules working

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1168]

**Comment by ritwik12** [comment]
@shiftkey Should we make Docs accessible too? Such as including a link to those in README or creating a wiki tab for it.

**Comment by shiftkey** [comment]
Two things come to mind:

 - update the `README.md` to link to the docs section
 - write a proper `CONTRIBUTING.md` that details about contributing to the client-side functionality and links to the specific documentation worth reading

**Comment by ritwik12** [comment]
@shiftkey Second one should be more appropriate.

**Comment by ritwik12** [comment]
@jackycodes You can have a look here, will be useful for your project.
