### ISSUE TITLE
Update link to esfiddle repository's issues

### ISSUE THREAD

**Issue by j-dover** [up-for-grabs/up-for-grabs.net#1240]
Hello all,

As I was browsing the Up-for-Grabs website, I noticed that the link to the esfiddle repository's issues page goes to its [old repo](https://github.com/esfiddle/esfiddle/labels/up-for-grabs) instead of its new repository. 

The [old repository](https://github.com/esfiddle/esfiddle) mentioned that it is now being developed on this [new repository](https://github.com/esfiddle/site).

I am not affiliated with esfiddle, but I noticed this as I was looking for a project to contribute to.

**Comment by ritwik12** [comment]
Got it, I will update. Thanks a lot for informing.

**Comment by shiftkey** [comment]
@j-dover @ritwik12 I'm going to close this out as the issue https://github.com/esfiddle/site/issues/43 should be enough to track what needs to be changed.

If someone would like to make the change, this is the relevant contents to update:

https://github.com/up-for-grabs/up-for-grabs.net/blob/5d4c4c45f22e644583eb8d984b4e12700a6a9706/_data/projects/esfiddle.yml#L10-L12

**Comment by joshghent** [comment]
Hi! Sorry this is my fault! I have submitted a PR here! https://github.com/up-for-grabs/up-for-grabs.net/pull/1255
Hope to have your help @j-dover - thanks for reporting this problem - open source wouldn't be possible without people like you ⭐
