### ISSUE TITLE
Cleanup repo

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1259]
I saw lots of image files and other files lying around in the repo outside of directories, It will be better to keep them in directories to keep repo clean.

**Comment by ritwik12** [comment]
While solving this issue better not to break things.

**Comment by SeanKilleen** [comment]
@ritwik12 can you elaborate a little further on what else you'd like cleaned up? I've got the icons as part of #1274 but am not sure what your other goals might be for this.

**Comment by ritwik12** [comment]
@SeanKilleen Yeah, thanks for that. I mean with every other file which might be lying here and there without any logic. This issue mainly concerns the better file structure or hierarchy to keep files of a project in open source. For eg: The same way we keep all CSS files in style named folder and main files in src folder for a website. Meaning to reduce as many files lying outside of directories as possible.

**Comment by shiftkey** [comment]
@ritwik12 as it's not clear to me what else needs to be done, I'm going to close this out due to inactivity. Please open new issues if there is anything else that needs work here.
