### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [up-for-grabs/up-for-grabs.net#1343]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`Homebrew-Cask.yml`](https://github.com/up-for-grabs/up-for-grabs.net/blob/ed20e2670ff3e1dd672660201b5814e91a9ee479/_data/projects/Homebrew-Cask.yml). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by shiftkey** [comment]
@reitermarkus I went ahead and made the change in #1344
