### ISSUE TITLE
Welcome Hacktoberfest Visitors!

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1359]
It's great to see [up-for-grabs.net](https://up-for-grabs.net/#/) listed as a resource for starting with Open Source at [Hacktoberfest](https://hacktoberfest.digitalocean.com/details).

[Readme.md](https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/README.md) should clear all the doubts about contributing and how it all works, still if anyone has any doubt or question please feel free to ask here.

### A small request
As this is a really good place for new contributors, that's why requesting all to maintain that and don't send test or spam PRs just for the sake of clearing Hacktoberfest. We have already started receiving such kind of PRs when Hacktoberfest isn't even started yet.

Hacktoberfest is meant to motivate new contributors in Open Source, there are awesome projects out there and also at [up-for-grabs.net](https://up-for-grabs.net/#/) on which anyone can work easily.

We would love contributions from everyone and ready to help you.

**Comment by shiftkey** [comment]
@ritwik12 thanks for the heads up - I'm going to pin this and tweak the title so that others are more likely to see it!

**Comment by AllanOcelot** [comment]
Let's hope some of these new faces stick around and help out with maintaining this Repo after Hacktoberfest 🥇

**Comment by ritwik12** [comment]
I believe many would @AllanOcelot, We did :)

**Comment by shiftkey** [comment]
This has wrapped for another year - thanks to everyone for getting involved!
