### ISSUE TITLE
Issue count not working

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1369]
Issue count is shown `?!` instead of the total number of issues.

**Comment by shiftkey** [comment]
@ritwik12 which project? This is the fallback behaviour when we can't hit the GitHub API to get the issue count:

 https://github.com/up-for-grabs/up-for-grabs.net/blob/41478a0be4002caff123b8668dafc6b073de4473/javascripts/main.js#L233-L235

**Comment by ritwik12** [comment]
All projects for me

**Comment by ritwik12** [comment]
<img width="1463" alt="Screenshot 2019-09-27 at 6 43 39 AM" src="https://user-images.githubusercontent.com/20038775/65773984-348eec00-e0f2-11e9-8efc-9a0ec7d48fc1.png">

**Comment by ritwik12** [comment]
@shiftkey Now, as we have issue count in Stats for every project, let's fetch this directly from there. if we are facing issues with GitHub API

**Comment by shiftkey** [comment]
@ritwik12 looks like you're being rate-limited #261 and I think #1346 is the long-term solution for that. Please test out that PR and see how it feels.

**Comment by ritwik12** [comment]
@shiftkey Got that, thanks. Checked and it works well!!

**Comment by ritwik12** [comment]
Let's close this after #1346 @shiftkey
