### ISSUE TITLE
Perhaps Wrap The Project Name

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#137]
![screen shot 2014-12-01 at 4 46 37 pm](https://cloud.githubusercontent.com/assets/359239/5241782/a7ec4ba6-7979-11e4-9f62-e46fcf5efcee.png)

Give that second column a chance to breathe!

**Comment by ChrisMissal** [comment]
How about this?

![image](https://cloud.githubusercontent.com/assets/67798/5483197/c2f23c28-8633-11e4-92b7-e88b354dfb87.png)

/cc @shiftkey @dahlbyk

**Comment by shiftkey** [comment]
@ChrisMissal I like it!

Perhaps the whitespace between the title and description can be reduced as well...

**Comment by ChrisMissal** [comment]
Good call, here we go:

![image](https://cloud.githubusercontent.com/assets/67798/5483355/026ce978-8636-11e4-98a2-5a4b27148b31.png)

Thoughts @shiftkey?
