### ISSUE TITLE
 Run failed

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1375]
@shiftkey I am getting mails regarding:

`Run failed: Validate Docker - gh-pages`
`Run failed: Validate JS - gh-pages`
`Run failed: Validate Site - gh-pages `

Please check

**Comment by shiftkey** [comment]
What's the comment in the footer of the email? Here's one from when an Action ran on a branch that I created:

<img width="408" src="https://user-images.githubusercontent.com/359239/65875972-bd11c480-e35e-11e9-9450-5d6ae5e4584d.png">

I've not really looked into how Actions generate and target these notices when things fail, but there's also a link there that might help you configure it.

**Comment by shiftkey** [comment]
Click that link to find your notification settings:

<img width="463" src="https://user-images.githubusercontent.com/359239/65878596-d584dd80-e364-11e9-9414-28eeba9f3cc8.png">

If you don't care about them at this point, just uncheck all the items...

**Comment by ritwik12** [comment]
@shiftkey I am not concerned about notifications, It is good for me. but failures that it is showing. Are those failures expected?

**Comment by shiftkey** [comment]
@ritwik12 these are the replacement TravisCI checks that we previously had in place, so I believe they are good to keep an eye on.

**Comment by shiftkey** [comment]
I think I understand the problem here -  you're seeing these reports come in for a couple of forks in the project too?

I've traced this to some behaviour in GitHub Actions where a specific GitHub App is installed, and reported this to the team to see if we can get it fixed as it shouldn't run in this situation.

**Comment by ritwik12** [comment]
Ohh, I see. Thanks, Do you want this to be open or we good to close? Please feel free to close

**Comment by shiftkey** [comment]
Yeah, if it's just occurring for the two of us then I don't think it's worth keeping open while it's being investigated.
