### ISSUE TITLE
review current projects without active label

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#1444]
The [last run](https://github.com/up-for-grabs/up-for-grabs.net/commit/ac240731d0d419ded71ab5f1d136be9e3e1fdb83/checks?check_suite_id=253451341) of our update stats action found these repositories that didn't have the label we expected:

> ~Cannot find label 'good first issue' for project 'OpenRCT2/OpenRCT2'~ - #1448
~Cannot find label 'Help wanted' for project 'matomo-org/matomo'~ - #1448
~Cannot find label 'Help wanted' for project 'isubasinghe/COMP30022-frontend'~ - #1449
~Cannot find label 'Up for grabs' for project 'Azure/azure-sdk-for-java'~ - #1470
~Cannot find label 'help wanted' for project 'tldr-pages/tldr'~ - #1449

To resolve these, we should:

 - find the project file under `_data/projects` that uses this repository
 - check the Labels list on GitHub to see why it cannot be found any more
 - if it looks like a typo, update the file to correct the typo
 - if it looks like the label was renamed, update the file to use a new label
 - ensure the `upforgrabs.link` URL is also correct
 - if no label can be found, delete the file from the repository

Don't worry about doing one PR per file - happy to batch these up into a single PR review.

**Comment by JoaoManoel** [comment]
Working on this! 😄

**Comment by JoaoManoel** [comment]
I've added the "OpenRCT2" and "matomo". 

I didn't find the COMP30022-frontend yml file.

I will leave the "azure-sdk-for-java" and "tldr" to another person. 

Thank you 👍

**Comment by filipe-gomes** [comment]
I can jump in and do the "azure-sdk-for-java" and the "tldr"

**Comment by shiftkey** [comment]
@JoaoManoel @filipe-gomes thanks for jumping in.

I'll update the issue description as we find and propose fixes.

**Comment by XxZhang2017** [comment]
Hi, I just got here. May I get the task for "tldr" ?

**Comment by shiftkey** [comment]
@XxZhang2017 `tldr` has been addressed in #1449 - the only one not claimed yet is `Azure/azure-sdk-for-java`

**Comment by shiftkey** [comment]
I think we're good to close this out.

Thanks @JoaoManoel and @filipe-gomes for picking this up, and @XxZhang2017 for your interest in getting involved!

**Comment by XxZhang2017** [comment]
> @XxZhang2017 `tldr` has been addressed in #1449 - the only one not claimed yet is `Azure/azure-sdk-for-java`

OH, thanks. I hope that I can do something in other openings.
