### ISSUE TITLE
Request to update README Add to Project sample code

### ISSUE THREAD

**Issue by codingcrystals** [up-for-grabs/up-for-grabs.net#1465]
@shiftkey In the README under [Add a Project](https://github.com/up-for-grabs/up-for-grabs.net#add-a-project), it has this line as the sample code:

`link: *URL where users can view the tasks -- e.g. https://github.com/username/project/labels/up%20for%20grabs*`

May I submit a PR to remove the trailing `*`? You commented in my [PR#1451](https://github.com/up-for-grabs/up-for-grabs.net/pull/1451#discussion_r331995779) that this causes the URL to be incorrect.

**Comment by shiftkey** [comment]
@crystal-dawn I'm 👍 to revisiting that text.

It's meant to indicate a placeholder value rather than a whole sentence, and it sounds like we can make that clearer here.

**Comment by codingcrystals** [comment]
That makes sense. I'm lazy I just copy/paste 😊

**Comment by shiftkey** [comment]
Resolved by #1481
