### ISSUE TITLE
all-contributors 

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1475]
@shiftkey When did we started following "all-contributors"? I am not able to track it under issues or PRs, did you commited that directly? Also, with this we will be adding contributors to the list from now on? Please let me know how are we going to follow this and we can keep this Issue for tracking purposes for the users looking for an answer about how to be in that list.

**Comment by shiftkey** [comment]
@ritwik12 apologies for not writing up an issue sooner - haven't had a chance to braindump my thoughts.

This idea came from stumbling across [allcontributors.org](https://allcontributors.org) as a way to simplify tracking contributors to this project in a way that overlaps with the README improvements proposed.

I installed their GitHub App into this project and have experimented with the tooling to get a feel for how it fits together. If we decide to go in a different direction to this, it's pretty easy to clean up.

**Comment by ritwik12** [comment]
Great, I will keep it in mind, Thanks
