### ISSUE TITLE
upgrade and test latest version of promise-polyfill

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#1490]
1. Change the version in this line to `@8.1.3` based on the latest version listed on NPM: https://www.npmjs.com/package/promise-polyfill

https://github.com/up-for-grabs/up-for-grabs.net/blob/65c5598277e639715b5897c7c0a7ddeca9dd263f/javascripts/app.js#L12-L13

2. [test locally, if possible](https://github.com/up-for-grabs/up-for-grabs.net#testing-the-site-locally)

3. Commit, push, open a PR with the change

4. Test the Netlify deploy URL (see the PR status list) and comment in the PR based on what you uncover

<img width="709"  src="https://user-images.githubusercontent.com/359239/66489914-bc77dd00-ea86-11e9-9d51-945cbe5814e8.png">

**Comment by Yeshwanthyk** [comment]
Hi, I would like to work on this? Is it open?

**Comment by shiftkey** [comment]
@Yeshwanthyk it looks like we have an open PR #1498 which I'm reviewing at the moment
