### ISSUE TITLE
[RFC] leveraging all-contributors integration to display contributors in README

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#1493]
You might have noticed some recent changes to the [README](https://github.com/up-for-grabs/up-for-grabs.net#contributors-):

<img width="939" src="https://user-images.githubusercontent.com/359239/66495181-390eb980-ea8f-11e9-8a99-b478397c72a6.png">

This is an experiment related to #1368 to address two things:

 - acknowledge contributors who help out with keeping the project going
 - encourage contributions that aren't necessarily code-focused

I'm focused on three specific contributions as part of this experiment:

 - bugfixes and enhancements - making the site better
 - content changes - ensuring project data and documentation is up to date
 - reviewer - users who help out with verifying changes and providing feedback

I've avoided "people who submit projects" in this experiment because I'm looking to encourage contributions that make our lives easier **in the near term**.

The integration itself is pretty straightforward, and this is easy to revert if we want to do something different, but it felt like a fun and easy way to leverage the README and thank our contributors. I plan to work my way back through older PRs which were notable contributions and add them to the list.

**Comment by ritwik12** [comment]
That sounds great @shiftkey. I will keep it in Mind while merging PRs.

**Comment by shiftkey** [comment]
Gonna close this out for now but please comment if you have any additional questions about this.
