### ISSUE TITLE
resolve no-var violations in javascripts/projectsService.js

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#1514]
We have some very old ESLint rules that I'd like to clean up, and our use of `var` is one of them. ES6 introduces `let` and `const` as a way to make clearer when a variable can be used, and I'd like to reduce our use of `var` where we don't need it:

If you know a bit about JS you can help out by following these steps:

 - create a new branch from `gh-pages`
 - in `javascripts/projectsService.js` add this comment at the top of the file, before any source code:

```js
/* eslint no-var: [ "error" ] */
```

 - in a terminal, run `npm run lint`, which should emit a bunch of violations:

```
$ npm run lint

> up-for-grabs.net@1.0.0 lint /Users/shiftkey/src/up-for-grabs.net
> eslint javascripts/*.js tests/**/*.js


/Users/shiftkey/src/up-for-grabs.net/javascripts/projectsService.js
    8:3  error  Unexpected var, use let or const instead  no-var
   12:3  error  Unexpected var, use let or const instead  no-var
   ...
```

 - run `npm run lint-fix` to fix whatever can be automatically tidied up
 - review and address the remaining violations manually
 - run `npm run prettier-fix` to ensure the formatting of the changes is fine
 - [test the site locally](https://github.com/up-for-grabs/up-for-grabs.net#testing-the-site-locally)
 - commit the changes and open a PR
 - test out the Netlify deploy site (click the `Details` link) and confirm the client-side functionality is still working

<img width="709" src="https://user-images.githubusercontent.com/359239/66651591-c70eaf80-ec09-11e9-85bc-a8c58d81e2be.png">

**Comment by firfircelik** [comment]
@shiftkey I can take this.

**Comment by Sayan-dev** [comment]
i would like to work on it

**Comment by shiftkey** [comment]
@Sayan-dev I haven't heard from @firfircelik about how they're progressing on this but feel free to take a shot at it and submit a PR.

**Comment by firfircelik** [comment]
@shiftkey sorry, I was away from my pc :/ I can handle it right now.
