### ISSUE TITLE
resolve "prefer-arrow-callback" violations in javascripts/fetchIssueCount.js 

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#1517]
We have some very old ESLint rules that I'd like to clean up, and our use of `var` is one of them. ES6 introduces `let` and `const` as a way to make clearer when a variable can be used, and I'd like to reduce our use of `var` where we don't need it:

If you know a bit about JS you can help out by following these steps:

 - create a new branch from `gh-pages`
 - in `javascripts/fetchIssueCount.js` add this comment at the top of the file, before any source code:

```js
/* eslint prefer-arrow-callback: [ "error" ] */
```

 - in a terminal, run `npm run lint`, which should emit a bunch of violations:

```
$ npm run lint

> up-for-grabs.net@1.0.0 lint /Users/shiftkey/src/up-for-grabs.net
> eslint javascripts/*.js tests/**/*.js


/Users/shiftkey/src/up-for-grabs.net/javascripts/fetchIssueCount.js
   11:46  error  Unexpected function expression  prefer-arrow-callback
  167:24  error  Unexpected function expression  prefer-arrow-callback
   ...
```

 - run `npm run lint-fix` to fix whatever can be automatically tidied up
 - review and address the remaining violations manually
 - run `npm run prettier-fix` to ensure the formatting of the changes is fine
 - [test the site locally](https://github.com/up-for-grabs/up-for-grabs.net#testing-the-site-locally)
 - commit the changes and open a PR
 - test out the Netlify deploy site (click the `Details` link) and confirm the client-side functionality is still working

<img width="709" src="https://user-images.githubusercontent.com/359239/66651591-c70eaf80-ec09-11e9-85bc-a8c58d81e2be.png">

**Comment by r0dq** [comment]
I'll work on this one.

**Comment by r0dq** [comment]
Pr submitted. This is my first PR so please let me know if there is something that i've missed.
