### ISSUE TITLE
investigate and resolve warnings when updating project stats

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#1521]
We're not able to generate stats for these two repositories:

> ~~Cannot find repository for project 'isubasinghe/COMP30022-frontend'~~ #1524 
Cannot find label 'up for grabs' for project 'crystal-dawn/job-requirements' #1531

To resolve these, we should:

 - find the project file under `_data/projects` that uses this repository
 - check the Labels list on GitHub to see why it cannot be found any more
 - if it looks like a typo, update the file to correct the typo
 - if it looks like the label was renamed, update the file to use a new label
 - ensure the `upforgrabs.link` URL is also correct
 - if no label can be found, delete the file from the repository

Don't worry about doing one PR per file - happy to batch these up into a single PR review.

**Comment by XxZhang2017** [comment]
Hi, may i take this issue? I have update the stat of the project 'isubasinghe/COMP30022-frontend'.

**Comment by shiftkey** [comment]
@XxZhang2017 I've merged in #1524 which addresses that issue, and feel free to open a second PR when you figure out what's happened with the other one.
