### ISSUE TITLE
Adding Github Authentication

### ISSUE THREAD

**Issue by mkkhedawat** [up-for-grabs/up-for-grabs.net#1532]
I see many issues circling around improving UX via activity stats. It seems to me that the first step towards making them work in realtime is using Github APIs. 

Has adding authentication to up-for-grabs.net been considered in the past? Given that unauthenticated hits limit to 60 req/hour.

I will be open to PR.

**Comment by shiftkey** [comment]
> Has adding authentication to up-for-grabs.net been considered in the past? Given that unauthenticated hits limit to 60 req/hour.

This has come up, but it didn't really progress. I ended up generating the stats as a periodic task (https://github.com/up-for-grabs/up-for-grabs.net/issues/1329 has the back story) which circumvents the need for the browser to use the GitHub API (I can see us cleaning that up eventually).

**Comment by shiftkey** [comment]
See #261 and #285 for related discussions

**Comment by mkkhedawat** [comment]
I see, wasn't aware that Github Actions support cron.

**Comment by shiftkey** [comment]
@mkkhedawat correct, check out the docs https://help.github.com/en/articles/workflow-syntax-for-github-actions#onschedule

**Comment by shiftkey** [comment]
@mkkhedawat given we have #175 and #285 which track ideas around project stats, and we have Actions to run periodically to perform authenticated API actions, I don't see the value in us making the user authenticate (which requires more infrastructure to handle the OAuth flow and manage tokens created on behalf of the user). Any objections to closing this out?

**Comment by mkkhedawat** [comment]
@shiftkey should be good to close.
