### ISSUE TITLE
Visual F# Tools has moved

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#154]
They've migrated the project to GitHub, but the `up-for-grabs` tag has not. What to do?

cc @latkin @dsyme @forki for contacts who can help

**Comment by forki** [comment]
I think there isn't a up-for-grabs, yet.

**Comment by shiftkey** [comment]
If it's not intended to be supported, I can :fire: the link. Otherwise I'll leave this open until it appears.

**Comment by latkin** [comment]
We will add it, just haven't gotten around to it yet. Hopefully we will do a better job of this on github than we did on Codeplex :smile:

**Comment by shiftkey** [comment]
@latkin :sparkles:

**Comment by latkin** [comment]
Behold: https://github.com/Microsoft/visualfsharp/labels/Up%20for%20Grabs

**Comment by shiftkey** [comment]
![](http://pixel.nymag.com/imgs/daily/vulture/2013/08/07/colbert%20gifs/colbert1.o.jpg/a_560x0.jpg)

**Comment by PatrickMcDonald** [comment]
I think this should be fixed in #174

**Comment by shiftkey** [comment]
Fixed in #174
