### ISSUE TITLE
Crazy Idea: File per Project

### ISSUE THREAD

**Issue by dahlbyk** [up-for-grabs/up-for-grabs.net#158]
https://github.com/dahlbyk/up-for-grabs.net/pull/156#issuecomment-72758489

http://jekyllrb.com/docs/datafiles/ seems to suggest we could split our monolithic `projects.yml` into separate files within a `projects/` directory. I wonder if `{{ site.data.projects | jsonify }}` would continue to Just Work™?

TODO:
- [ ] See if this can work
- [ ] Explode `projects.yml` into separate files

**Comment by shiftkey** [comment]
I'll do a quick spike to confirm this crazy idea works.

**Comment by shiftkey** [comment]
Sadly `site.data.projects` is now a hash-table, with the key being the filename:

```
{
   "albacore":[
      {
         "name":"albacore",
         "desc":"Albacore is a professional quality suite of Rake tasks for building .NET or Mono based systems.",
         "site":"http://albacorebuild.net/",
         "tags":[
            "F#",
            "C#",
            "C++",
            "VB",
            "Ruby",
            "buildsuite",
            "builds",
            "build",
            "packaging",
            "rake",
            "mono"
         ],
         "upforgrabs":{
            "name":"help wanted",
            "link":"https://github.com/Albacore/albacore/labels/help%20wanted"
         }
      }
   ],
   "validator":[
      {
         "name":"Validator",
         "desc":"Port of validator.js",
         "site":"https://github.com/ByteBlast/Validator",
         "tags":[
            "C#"
         ],
         "upforgrabs":{
            "name":"help wanted",
            "link":"https://github.com/ByteBlast/Validator/labels/help%20wanted"
         }
      }
   ]
}
```

If we can just turn the values for each entry into a collection, we'll be fine...

**Comment by shiftkey** [comment]
Alright, I've got this working with bit of JS hackery. Follow along here #160
