### ISSUE TITLE
review projects with missing labels

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#1674]
Found these on a recent check of the labels:

```
Cannot find label 'hacktoberfest' for project 'OpenRCT2/OpenRCT2'
Cannot find label 'good first issue' for project 'raiden-network/raiden'
Cannot find label 'hacktoberfest' for project 'home-assistant/home-assistant.io'
```

This suggests:

 - a label is no longer used on the project
   - often this just means finding a suitable label to use in it's place
 - the label name has changed (either a typo or a full rename)
   - check the labels listed for the project, update our listing with the better match
 - the label has been dropped
   - probably a sign that a different label is now preferred
   - if no label looks suitable, this indicates the project is no longer interested in participating

**Comment by XxZhang2017** [comment]
@shiftkey I have a quick question.
For the project 'OpenRCT2' they have remove the label 'hacktoberfest'. The candidate label are 'help wanted' , 'good first issue'. Then which one will be replace with here ? I check the issue updated date for candidate label issue. They are updated last year. It is kind of old. Does it matter ?

**Comment by shiftkey** [comment]
@XxZhang2017 I had a look at these issues, sorted recently updated:

 - [`good first issue`](https://github.com/OpenRCT2/OpenRCT2/issues?q=is%3Aopen+label%3A%22good+first+issue%22+sort%3Aupdated-desc) - 19 open issues, 15 that have been updated in the last year
 - [`help wanted`](https://github.com/OpenRCT2/OpenRCT2/issues?q=is%3Aopen+label%3A%22help+wanted%22+sort%3Aupdated-desc) - 7 open issues, 0 updated in the last year

So I think `good first issue` is the better choice here. Does that help?

**Comment by XxZhang2017** [comment]
@shiftkey Yes! Thank you!

**Comment by XxZhang2017** [comment]
@shiftkey There is no label suitable for the project 'raiden-network'. It may not be interested in participating. Should we remove the .yml of this project ?
As for 'home-assistant/home-assistant.io' I can find the labels 'hacktoberfest' in their project.

I want some guide to fix them. I can take this issues.

**Comment by shiftkey** [comment]
@XxZhang2017 what about [`Tag / Good First Issue`](https://github.com/raiden-network/raiden/labels/Tag%20%2F%20Good%20First%20Issue)?

**Comment by XxZhang2017** [comment]
@shiftkey For the project OpenRCT2, there is no `hacktoberfest` label anymore. I think `good first issue `is the better choice to replace the `hacktoberfest`. What do you think of it ?

**Comment by XxZhang2017** [comment]
@shiftkey Hi, what I did for this issue is "changing the label 'hacktoberfest' for project OpenRCT2/OpenRCT2 to 'good first issue', deleting file raiden.yml". If it is okay, please let me create a PR. Thanks.

**Comment by shiftkey** [comment]
@XxZhang2017 let's talk about the changes proposed in #1692 

> As for 'home-assistant/home-assistant.io' I can find the labels 'hacktoberfest' in their project.

I overlooked this comment - apologies! I think [help wanted](https://github.com/home-assistant/home-assistant.io/labels/Help%20wanted) for this label is a decent replacement, and judging by the screenshot it should be `Hacktoberfest` (with an upper-case H):

<img width="1053" src="https://user-images.githubusercontent.com/359239/68894544-dfd51e00-06fd-11ea-92e2-a1ecaf08a92f.png">
