### ISSUE TITLE
More project info

### ISSUE THREAD

**Issue by dahlbyk** [up-for-grabs/up-for-grabs.net#17]
Before too many projects are added, should we move beyond a simple list? I'm thinking we can use a table with a few columns:
- Project (linked)
- up-for-grabs tag name (linked)
- Tags (e.g. Glimpse might use "web, diagnostics, asp.net, c#, javascript")
- Description/Notes

I figure we can eventually enable filtering of the ever-growing list based on tags.

Anything else?

**Comment by shiftkey** [comment]
:thumbsup: to tags
:thumbsup: to brief description
:thumbsup: to filtering

**Comment by akoeplinger** [comment]
:+1: sounds like a good idea

**Comment by ChrisMissal** [comment]
Yes to all, but I would like to see it stay as pure HTML/CSS/JS. Can the "table" be a JSON file that is filtered/searched via JS?

**Comment by dahlbyk** [comment]
Moving into JSON would work, but for now I think we could get away with an HTML table with an embedded microformat:

``` html
<table>
  <tr>
    <td><a class="proj" href="https://github.com/dahlbyk/up-for-grabs.net">up-for-grabs.net</a>
        <a class="label" href="https://github.com/dahlbyk/up-for-grabs.net/issues?labels=up-for-grabs">up-for-grabs</a></td>
    <td><p class="desc">A site to explore open source projects and jump in!</p>
        <p class="tags">javascript, oss, web</p></td>
  </tr>
  ...
</table>
```

**Comment by ChrisMissal** [comment]
Oh yeah, certainly.

**Comment by akoeplinger** [comment]
This sounds like a perfect fit: http://jekyllrb.com/docs/datafiles/

Will try how that works :smile: 

_edit_ looks like that only works for Jekyll sites, which this is not yet. Might however be a good idea to turn it into one.

**Comment by dahlbyk** [comment]
@akoeplinger that seems like a good way to go, to more easily maintain consistent markup. I'll admit I've not actually used Jekyll - is that migration something you could take on?

**Comment by dahlbyk** [comment]
I'm debating if it's worth separating out the project and label links - the project link makes it easier to view the readme, but maybe the description included here would be sufficient?

If we don't go with separate links, a list may be sufficient:

``` html
<ul>
    <li><a class="proj" href="https://github.com/dahlbyk/up-for-grabs.net/issues?labels=up-for-grabs">up-for-grabs.net</a>
        <p class="desc">A site to explore open source projects and jump in!</p>
        <p class="tags">javascript, oss, web</p></li>
    ...
</ul>
```

**Comment by ursic** [comment]
:+1: to list
Maybe an OS icon as well?

**Comment by dahlbyk** [comment]
What do you mean by OS icon? Like a project logo?

**Comment by ursic** [comment]
Operating system icon. In case anyone is almost exclusively a Linux/Windows/OSX dev, for example ;)

**Comment by dahlbyk** [comment]
> Operating system icon. In case anyone is almost exclusively a Linux/Windows/OSX dev, for example ;)

Ah yes - good idea. I wonder if we could just establish a tag convention for OS-specific projects?

**Comment by ursic** [comment]
So, put OS either at the beginning or the end of the tags: Windows, javascript, css.
And then have a line or two of JS to parse the tags and put up respective icon when it finds an OS.
I imagine additional visual icon would be faster to parse by humans?

**Comment by akoeplinger** [comment]
@dahlbyk It's actually pretty easy, I moved the project data to a YAML file in my fork: https://github.com/akoeplinger/up-for-grabs.net

Here's how it looks like with a table (+ a few example descriptions/tags taken from NuGet.org): http://akoeplinger.github.io/up-for-grabs.net/

I'd prefer keeping a seperate link to the project site even though we have the description, as it provides a convenient shortcut to learn more about a project without having to search elsewhere.

**Comment by dahlbyk** [comment]
> I moved the project data to a YAML file in my fork

Love it - open a PR?

**Comment by akoeplinger** [comment]
Here you go: #29
