### ISSUE TITLE
add "needs work" label when commenting if problems are found

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1745]
@shiftkey Not much needed but would nice to have if it could be done easily
If we are confident with @shiftbot. It will be better to automatically add "needs work" label to those PRs on which @shiftbot suggests changes. 
> And I hope users are getting mail of @shiftbot giving suggestions after their PR submission.

**Comment by shiftkey** [comment]
@ritwik12 moving this to https://github.com/shiftkey/webhooks/issues/39 as that's where the change needs to be made.
