### ISSUE TITLE
Get description from GitHub API

### ISSUE THREAD

**Issue by khellang** [up-for-grabs/up-for-grabs.net#179]
It would be cool to keep the description up to date by fetching it from the GitHub API, to prevent cases like #178.

Ref: https://developer.github.com/v3/repos/#get

**Comment by shiftkey** [comment]
I started writing some Ruby over in #160 to migrate projects to the new structure - might whip up something similar afterwards for this...

**Comment by shiftkey** [comment]
Is it a fair assumption that these projects will want that? I don't mind whipping something up after I've got a proper data source for these projects, just curious how much value it'd add.

For reference, most of the updates I've had are for changing tags and URLs...

**Comment by khellang** [comment]
It could be worth making the `desc` node optional and have it fetch the description from GitHub instead. Given that you're able to extract the GitHub repo URL from somewhere...

**Comment by shiftkey** [comment]
Alright, as a starting data point we should investigate how many projects use a different description here to what they've defined on GitHub. If there's a high overlap, I'm interested in making this optional...

**Comment by khellang** [comment]
That's a good point. I think the less information (from GitHub) we need to duplicate here, the better. The question is, once/if we make `desc` optional, what happens to the projects that already have a `desc`?

**Comment by shiftkey** [comment]
They can keep it, for all I care. But it'd be really cool if new PRs would say "hey, you haven't provided a `desc` field, so this is what you'll see" and then screenshot and add a comment to the PR (okay, maybe a screenshot isn't necessary).

**Comment by shiftkey** [comment]
For the moment I'm going to leave this as a manual process, because plenty of projects seem to be happy to add a custom message here that isn't necessarily what is in the project description.

We can revisit this if we get an uptick in PRs that only change the description.
