### ISSUE TITLE
Splitted data files contain --- at top

### ISSUE THREAD

**Issue by akoeplinger** [up-for-grabs/up-for-grabs.net#186]
E.g. [angularjs.yml#L1](https://github.com/dahlbyk/up-for-grabs.net/blob/d70d4b6ffcd14bc89a8c88a9ff76456a47b11b1d/_data/projects/angularjs.yml#L1)

This looks like a mistake from the migration, we should just remove the `---` (unless it's needed for something?).

**Comment by shiftkey** [comment]
Yeah, it's a migration artefact. :thumbsup: to cleaning it up, but not super-urgent.
