### ISSUE TITLE
Is it possible to display a list of issues that do not have any pull requests?

### ISSUE THREAD

**Issue by jkodroff** [up-for-grabs/up-for-grabs.net#188]
If someone has already committed a PR to solve an issue ([example here](https://github.com/MehdiK/Humanizer/issues/388)), I think it'll still remain in the issue list shown on GH.  

Maybe this can be improved by one of the following:
1. If it's easy to construct a URL with the filter we want, tweak the link to the the tag in each project. OR...
2. If it's hard to formulate a link and we need to make multiple API calls, we could add a detail view to each project in UFG that has a section "What's Up For Grabs?" with a list on _untouched_ (code-wise) but tagged issues.

What do we think?

**Comment by dahlbyk** [comment]
From the [issue search docs](https://help.github.com/articles/searching-issues/), I don't see a built-in way to identify issues that have open PRs against them.

Even adding an API does not seem to help: I don't see a "referenced by PR" event in the events or comments streams for #158:
https://api.github.com/repos/dahlbyk/up-for-grabs.net/issues/158/comments
https://api.github.com/repos/dahlbyk/up-for-grabs.net/issues/158/events

But I can get a count of comments from the API call already in use on #163: https://api.github.com/repos/dahlbyk/up-for-grabs.net/issues?labels=up-for-grabs

**Comment by shiftkey** [comment]
Without doing a lot of processing of open PRs to find the issues references, or scanning the timeline events for each issue to find PR references, I'm not sure how else we'd achieve this. And we'd need infrastructure to do that which doesn't currently exist.

Gonna close this out to simplify things, but maybe one day this will be possible.
