### ISSUE TITLE
Update description for the project

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#2081]
wrt #1285 
```
This is a list of projects which have curated tasks specifically for new contributors. These are a great way to get started with a project, or to help share the load of working on open source projects. https://up-for-grabs.net/
Tags:  JavaScript, Ruby, good first issue, help wanted, up-for-grabs
```
This is just an example @shiftkey, please consider updating to the best.

**Comment by jrusbatch** [comment]
I updated the repo's description to be similar to the above in the meantime.

**Comment by ritwik12** [comment]
@jrusbatch Thanks a lot, will need tags also to make this project more searchable.

**Comment by shiftkey** [comment]
Those topics work - I've added them to the repository too.

Any other changes we should make while we're thinking about this area?

**Comment by ritwik12** [comment]
That should be good I think for now. Rest we have to work in #1285 regarding code changes and indexing. @shiftkey Feel free to close this.

Thanks @jrusbatch and @shiftkey
