### ISSUE TITLE
Support Design and Documentation

### ISSUE THREAD

**Issue by ChrisMissal** [up-for-grabs/up-for-grabs.net#212]
This is great for development issues, but I would love to see Up For Grabs support Design/UI/Logo issues as well as Documentation issues.

I don't know how this would look or change things. Maybe it's not the right place for it, but I thought I'd bring it up. Does anybody have ideas on how to support this or even if UFG is right for it?

**Comment by dahlbyk** [comment]
I'm not sure what sort of change might be useful on the UFG site itself, but in my mind non-dev tasks could absolutely be up-for-grabs on any given project. Anything that the maintainer(s) would like to help new contributors with, really.

**Comment by shiftkey** [comment]
Apologies for dusting off this discussion way after the fact:

@ChrisMissal would a separate tag be enough here? Or do things need to be more separated between development/design/UI/logo work (to name things arbitrarily) so that it's easier to find the right type of work you're interested in?

**Comment by ChrisMissal** [comment]
> Does anybody have ideas on how to support this or even if UFG is right for it?

657 days ago. I think we're probably okay to close this one :)
