### ISSUE TITLE
first-timers-only

### ISSUE THREAD

**Issue by kentcdodds** [up-for-grabs/up-for-grabs.net#216]
I wrote [a blogpost](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) about something that I've started recently. I'm wondering if there's any way we could make a section of this website that's designated for `first-timers-only` so people know where they can go to make their first contribution...

**Comment by kentcdodds** [comment]
I was about to tweet about this issue, but I think you'd wind up with a lot of +1 comments. If you want me to so you can gauge interest, then I will. Just prepare your inbox...

**Comment by shiftkey** [comment]
> I was about to tweet about this issue, but I think you'd wind up with a lot of +1 comments. 

That's fine.

**Comment by JasonLunsford** [comment]
+1 !

**Comment by jacobappleton** [comment]
+1

**Comment by gustavodegeus** [comment]
+1

**Comment by PillowPillow** [comment]
+1
It's a great initiative.

**Comment by gr2m** [comment]
+1 this is great!

**Comment by NealJones** [comment]
+1

**Comment by ChrisMissal** [comment]
+1

**Comment by shanselman** [comment]
I have firsttimersonly.com and I'd like work with @kentcdodds to make a one pager GHpages that would also point it to that theorectical new upforgrabs section. 

Also, I'm a chair of OSCON 2016 with @kelseyhightower and we're (very initially) brainstorming about doing a FirstTimersOnly hackathon/training sessions, so we could use this new section to promote it.

**Comment by kentcdodds** [comment]
Wow! That's awesome Scott! Let me know what I can do to help.
- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by shiftkey** [comment]
@shanselman @kentcdodds :wave: I'd love to use this thread to brainstorm ideas about implementing this. It definitely seems like there's interest to see this happen in some shape or form...

**Comment by shanselman** [comment]
@kentcdodds let's go offline, email me, we'll do the one pager, then we'll coordinate to feature UpForGrabs while they make a category/tags

**Comment by shiftkey** [comment]
:thumbsup:

**Comment by kentcdodds** [comment]
Done

**Comment by southpawjoe** [comment]
+1

**Comment by rubberduck203** [comment]
:+1:

**Comment by M-Zuber** [comment]
+1 for the idea.
Interesting angle on this idea might be to help first timers with pull requests on their projects.

**Comment by dahlbyk** [comment]
Along these lines, would it make sense for us to support filtering our project catalog by issue label (first-timers-only, up-for-grabs, jump-in, ...)?

**Comment by kentcdodds** [comment]
I don't think so... I think that the other ones denote the same concept: I'd accept a PR for an implementation that solves this issue.

Whereas `first-timers-only` denotes: I'm willing to hold your hand so you can make your first PR. This one's quite a bit easier than normal. Anyone who's already contributed to open source isn't allowed to touch this one...

**Comment by shiftkey** [comment]
@dahlbyk on the data side, I had thoughts to just have an opt-in property for the project YAML, like: `first-timers: yes` instead of Yet Another Label.

I guess the focus here is to signal that you're interested and able to provide that extra degree of support for newcomers or inexperienced contributors - and it would make it easy to filter without needing to be too clever with labels.

**Comment by kentcdodds** [comment]
Just to make sure we're on the same page... I think it's critical that there's a special label on the repo for `first-timer-only` issues. There's a huge difference in my repo with what I think is appropriate for a first timer and what I think is `up-for-grabs`.

First timer contributions are normally very small and easy (One was literally 10 characters or so). This makes it easier for the contributor to get the hang of the contribution _process_ rather than the _contribution itself_.

Also, some of my `up-for-grabs` issues would be very difficult to hold someone's hand on. Many (not all) first time contributors are pretty new to coding in general. For that 10 character contribution, I had to hold their hand through that implementation. Not a problem, but it would be if the implementation were more difficult.

Not sure if you were suggesting otherwise. Just wanted to be clear what I am hoping for.

**Comment by shanselman** [comment]
@shiftkey I have to agree with @kentcdodds that while it is YAL it's far easier to use a label for this (and we may be able to turn this into a larger Movement (TM) and get GitHub to make first-timer-only something special, maybe a badge or emoticon, ahem, @haacked)

**Comment by shiftkey** [comment]
@shanselman well then it's stupendously easy to link directly to that YAL here:

> http://up-for-grabs.net/#/tags/first-timers-only

I'm down for talking about how to spread the good word and find these projects. This is probably where some Proper-Docs-I-Keep-Meaning-To-Write-For-This-Site might help.

**Comment by shanselman** [comment]
Cool, does that pull all Open Issues from GH @shiftkey? https://github.com/search?utf8=%E2%9C%93&q=label%3Afirst-timers-only (yes this query pulls closed ones also)

**Comment by shiftkey** [comment]
@shanselman correct (see https://github.com/dahlbyk/up-for-grabs.net/pull/163) - we could probably be cleverer and use a proxy service so that not everyone needs to fetch it for each project (you can expire your unauthenticated API access rather quickly), but it's relatively real-time...

**Comment by haacked** [comment]
> get GitHub to make first-timer-only something special, maybe a badge or emoticon, ahem

Interesting. I'll ask around to see if that's something GitHub might be interested in doing officially.

In the meantime, I'm happy to drop in and create a bespoke animated gif to celebrate first time contributions.

![yes-fist-pump](https://cloud.githubusercontent.com/assets/19977/9177005/8e9971fc-3f43-11e5-9c06-ada39da5301c.gif)

**Comment by kentcdodds** [comment]
Awesome :-)

**Comment by shiftkey** [comment]
it's been a while since this discussion started, but GitHub did ship this little bit of polish recently:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Maintainers will now see &quot;first-time contributor&quot; badges if it&#39;s the author&#39;s first pull request to the project. Be sure to welcome them! <a href="https://t.co/8wlkDNSO9r">pic.twitter.com/8wlkDNSO9r</a></p>&mdash; Ben Balter (@benbalter) <a href="https://twitter.com/benbalter/status/845305265159376896">March 24, 2017</a></blockquote>

![](https://cloud.githubusercontent.com/assets/359239/25983188/51dca2e8-3726-11e7-8814-d9724260b567.jpg)

**Comment by shiftkey** [comment]
Closing this out to get stuff off my plate, but feel free to comment if you've got additional ideas.
