### ISSUE TITLE
Point to Yeoman Generator

### ISSUE THREAD

**Issue by ChrisMissal** [up-for-grabs/up-for-grabs.net#220]
I know it's trivial, but I built a Yeoman Generator (mostly to learn more about them) to generate files for up-for-grabs:

https://github.com/ChrisMissal/generator-up-for-grabs

Any interest in including the instructions to use it? It would look something like this:

```
npm install -g yo
npm install -g generator-up-for-grabs
yo up-for-grabs
```

**Comment by shiftkey** [comment]
I think this is could be added to the README. Thoughts @dahlbyk @jrusbatch?

**Comment by dahlbyk** [comment]
:+1:
