### ISSUE TITLE
needs to let the user know when there are no search results

### ISSUE THREAD

**Issue by nindroz** [up-for-grabs/up-for-grabs.net#2209]
when you pick certain tags and labels, if there is no results it should let the user know that because it is pretty confusing on what happened if nothing shows up

**Comment by creatorpiyush** [comment]
Can I work on this issue?

**Comment by ritwik12** [comment]
@nindroz Thanks for creating this issue. It would be useful to have this.

**Comment by ritwik12** [comment]
@creatorpiyush If @nindroz is not working on this. You may go ahead!!

**Comment by anksraws** [comment]
hy anyone working on this issue, or an i work on it ?

**Comment by ritwik12** [comment]
@anksraws Go ahead!!

**Comment by Aliecake** [comment]
looks like others stopped working on this? I'll take this.

**Comment by ritwik12** [comment]
@Aliecake Thanks

**Comment by ritwik12** [comment]
@Aliecake I had to revert #2378 as it broke the site. Please check what is getting messed up here.

<img width="1089" alt="Screenshot 2020-10-11 at 12 10 51 PM" src="https://user-images.githubusercontent.com/20038775/95687965-931eef00-0bbb-11eb-9373-0ffca31b0ce4.png">

**Comment by ghost** [comment]
Is there anything i can do that @Aliecake isnt already fixing?

**Comment by ritwik12** [comment]
@cernoit Hey, I guess @Aliecake got busy somehow. If you can check what @Aliecake missed in that PR and fix that. it would do this. Please feel free to discuss and send a PR.

**Comment by consolexyz** [comment]
can I work on this?

**Comment by ritwik12** [comment]
@Mosesobike Yes sure, please go ahead.

**Comment by mrpandya** [comment]
@ritwik12  is anyone working on this issue? If no, is there anything I can work on this issue?

**Comment by ritwik12** [comment]
@mrpandya For now nobody is working on this. You can work on it if interested. Please open a new PR or you can fix the bugs in  #2378.

**Comment by ritwik12** [comment]
Resolved by #2879
