### ISSUE TITLE
add a license to this repo

### ISSUE THREAD

**Issue by wolftune** [up-for-grabs/up-for-grabs.net#221]
I don't see a LICENSE file. Please choose a license. Since it is a website, I recommend AGPLv3+ so everyone who contributes knows that it will stay free/open always.

**Comment by shiftkey** [comment]
I'll be submitting a PR for this soon to address it, but think we need two different licenses:
- MIT for the current theme - it's largely still the default theme, [Slate](https://github.com/jasoncostello/slate), so I think we need to respect that license until we've looked at restyling the site.
- [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/) for the project listing content

The only controversial thing here is a lack of restriction on commercial work derived from this - some might have feels on this but I personally don't.

I'll try and get signoff from a quorum of those people who have submitted PRs to this license decision, so this might take a while.

**Comment by wolftune** [comment]
@shiftkey never ever have anti-commerce licenses, they are _super_ problematic and misguided. Lots of resources about that here: http://freedomdefined.org/Licenses/NC — in basically all cases, the SA (coyleft) part achieves what you want.

**Comment by dahlbyk** [comment]
I'm with @wolftune that SA is sufficient without NC. Aligning with theme license is reasonable as well. Just need to confirm with JS contributors that they're cool with the same.

**Comment by shiftkey** [comment]
@dahlbyk thanks for reminding me. I'll make sure to mention those people in the PR thread.

**Comment by shiftkey** [comment]
Oh, I fixed this in #252
