### ISSUE TITLE
some projects are out of maintenance from years, need to be removed or has label to indicate this

### ISSUE THREAD

**Issue by MahmoudMabrok** [up-for-grabs/up-for-grabs.net#2295]

**Comment by ritwik12** [comment]
@MahmoudMabrok We do that by removing DEPRECATED PROJECTS. We check for the ones archived or removed by the owner. Do you mean something else?

**Comment by shiftkey** [comment]
An example of how this works is https://github.com/up-for-grabs/up-for-grabs.net/pull/2285, and we currently detect:

 - repository redirects (it's nice to point ourselves to the new home)
 - archived projects (maintainers can mark a repository as archived which puts it into a read-only state)
 - missing projects (the maintainer may have deleted the repository or changed it to private)

We also track the "last updated" value for each project, which represents the last time an issue was created or updated:

https://github.com/up-for-grabs/up-for-grabs.net/blob/b9d3f2f3378e57b345e329fdc70410e5e6f594c9/_data/projects/100DaysofMLCode.yml#L19-L21

This could be a bit clearer in the site, and I'd love for someone else to do something better than my simple tooltip on hover:

<img width="332" src="https://user-images.githubusercontent.com/359239/92655266-827f0e80-f2c7-11ea-8558-76a892263b1c.png">

**Comment by ritwik12** [comment]
If we can show the Activity Graph of a repository on the Site, then that would be much better. This is one of the way I choose repositories to work on as I don't want my PR to just hang over there.
<img width="181" alt="Screenshot 2020-09-09 at 3 06 06 PM" src="https://user-images.githubusercontent.com/20038775/92659860-05936b00-f2ae-11ea-9397-142b4f6af146.png">

**Comment by ritwik12** [comment]
One of the way is to get PAST YEAR OF ACTIVITY by using `GET /repos/owner/repo/stats/commit_activity` and other stastics APIs as mentioned in https://docs.github.com/en/rest/reference/repos#statistics.

We can plot graphs once we get the metrics.

**Comment by MahmoudMabrok** [comment]
I think tooltip with the date of the last commit done on the repo is a enough for users of the website to know the activity of the repo.  
@ritwik12 @shiftkey

**Comment by ritwik12** [comment]
I think we don't have anything more to discuss here. Closing this one out.
