### ISSUE TITLE
Hide projects with no eligible issues by default

### ISSUE THREAD

**Issue by jkodroff** [up-for-grabs/up-for-grabs.net#233]
What do we think of an option "Include projects with no open issues" (off by default)?  (I'm making the assumption that most people would want those projects hidden.)  @dahlbyk might [notice a pattern](https://github.com/dahlbyk/posh-git/issues/205) here.

I don't remember the details of how the count was added in the first place, so I dig that this might be tricky or not feasible at all, but I figured it was worth an ask.

**Comment by shiftkey** [comment]
@jkodroff it's all driven by JS in the client (query the API, and store in local storage) so pre-emptively doing this is going to be tricky (maybe impossible).

I have some feels about moving this behaviour to a simple proxy API (that can do authenticated API calls and cache) which would also enable more complex analytics - one thing I'd like to track is measuring how many PRs are being merged (whether it is up-for-grabs or not might also be interesting) to indicate active projects.

I've got some bigger fish to fry in the short term, but if someone's feeling brave I'm happy to do a brain dump of this to kick things off at least...

**Comment by shiftkey** [comment]
If we can get to a point where we're able to reliably cache these stats (and we're not dealing with rate-limiting on the client) we could do client-side hiding fairly easily. But that requires a bunch of additional work first.

Gonna close this out to get stuff of my plate, but maybe we'll come back to it in the future.
