### ISSUE TITLE
Welcome Hacktoberfest Visitors!

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#2333]
Welcome, all participants. Thanks for visiting **up-for-grabs.net**

Please go through [README.md](https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/README.md), [Instructions to open a pull request](https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/docs/list-a-project.md) and [CONTRIBUTING.md](https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/.github/CONTRIBUTING.md)

These few links should answer all your doubts, If you still need help or face any issues please feel free to use this ISSUE as a Discussion where you can get help from other awesome contributors.

Please go through [Hacketoberfest Participation Details](https://hacktoberfest.digitalocean.com/details) to contribute better and follow the contributing guidelines. This would make our work much easier. I hope we will not mark even a single Pull request as **_"invalid"_**. Let's work together to reduce spam.

**Few Tips**
For most of you, this might be the first time contributing to Open Source. Wish you all lots of new learnings in this journey ahead. I hope some of you will find their interests and would help to make Open Source a better place for people to learn and contribute. In the beginning, most of you might find it tiring to get a good repository to contribute. Please hang on to that and you will surely get something where your skills will match. Use this time to Motivate yourself and give your best to do something new and Innovate. Help others whenever you can.

Me(@ritwik12) and @shiftkey will try our best to answer you and take a look at your PRs ASAP. Please be patient and we will be right there soon. We are happy for you all to be here and find projects that will help you in contributing to Hacktoberfest and eventually start your Open Source Journey.

**New Rules introduced as per Digital Ocean:**

```

1. Pull requests can be made in any participating GitHub-hosted repositories/projects.
2. Maintainers can opt-in to participate by classifying their projects with the hacktoberfest topic.
3. Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic and once they have been merged, approved by a maintainer or labelled as hacktoberfest-accepted. 
4. Additionally, any pull request with the hacktoberfest-accepted label, submitted to any public GitHub repository, with or without the hacktoberfest topic, will be considered valid for Hacktoberfest.

All valid pull requests prior to Oct 3 (when these rules were introduced) will be honored and counted toward completion of Hacktoberfest.
```

**Comment by luckyguy73** [comment]
Hello, according to this link the repo is supposed to have the topic "hacktoberfest" in order to be eligible as one of the 4 PR goal.  https://dev.to/devteam/happy-hacktoberfest-here-s-how-to-show-up-for-open-source-this-month-4cee
![image](https://user-images.githubusercontent.com/18206189/95032527-c61f2b00-066f-11eb-8de1-274a52690355.png)

**Comment by ritwik12** [comment]
@luckyguy73 Thanks for bringing this up to our knowledge. Things might have changed this time and we were not aware of that.
@shiftkey can you please add "hacktoberfest" to the topics of our repository for the Hacktoberfest duration i.e. only October.

**Comment by shiftkey** [comment]
@ritwik12 this is done, but if we continue to see spam PRs I'm willing to revisit and drop the label.

**Comment by ritwik12** [comment]
@shiftkey Thanks, Feel free to do so :)

**Comment by ritwik12** [comment]
@shiftkey Let's close this and remove the `hacktoberfest` from topics too.

**Comment by shiftkey** [comment]
Done!
