### ISSUE TITLE
Contributors section in README.md

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#2371]
@shiftkey We started with https://github.com/up-for-grabs/up-for-grabs.net#contributors- but then I think we stopped doing that. Due to that, it ended up having only a few people which does not look good.

I think we should either do it often to give credits to every deserving one or don't do it at all. What are your thoughts on this?

**Comment by shiftkey** [comment]
> I think we should either do it often to give credits to every deserving one or don't do it at all. What are your thoughts on this?

I wanted to focus on contributions that were not related to listing projects, with things like code and documentation that help keep the project going. If we've overlooked a contribution like that we can add them to the list.

We could add some words to that section to indicate what it's about, if that helps to clarify things...

**Comment by shiftkey** [comment]
#1493 also adds some extra context

**Comment by ritwik12** [comment]
@shiftkey Thanks for clarifying.
