### ISSUE TITLE
IE 11 compatibility issue, but is IE compatibility required?

### ISSUE THREAD

**Issue by es-rene99** [up-for-grabs/up-for-grabs.net#2442]
While working on #2441 I tested on IE 11, in the site's current state without any modifications:
![image](https://user-images.githubusercontent.com/43294836/97732107-a70f8f80-1a9b-11eb-95a8-2ca8dc5b778d.png)
It appears that the Projects script is not working, also my PR for #2441 uses semantic HTML5 elements which are not supported by IE8 or lower https://caniuse.com/html5semantic.

On the other hand I believe most developers use modern browsers, and this issue is not present in Edge, in the case is not necessary I believe the following meta can be removed from head.html as it's used in [few cases](https://stackoverflow.com/questions/6771258/what-does-meta-http-equiv-x-ua-compatible-content-ie-edge-do)
```html
<meta http-equiv="X-UA-Compatible" content="chrome=1" />
```
In any case if modifications are required, for this meta tag I suggest using "IE=edge" instead of Chrome=1 since this option was for using Chrome Frame which is already [retired.](https://blog.chromium.org/2013/06/retiring-chrome-frame.html) 

What are your thoughts?

**Comment by ritwik12** [comment]
@es-rene99 Thanks for opening this, Sorry for the delayed reply.

**is IE compatibility required?** 
It is always better to make the product platform-independent as long as it does not alter the quality on already running platforms. It would be better if it works the same way on IE too. But considering the amount of maintenance and code change it will need for that is an important point for discussion.

Please feel free to send PRs for making it IE compatible, I will mark this issue as DISCUSSION to have more better views here.

**Comment by jalaniz1** [comment]
**is IE compatibility required?** 

Almost two years later and IE is now officially retired 😄. IMO, targeting evergreen browsers seems like a better use of our time now adays.

[https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/#:~:text=After%2025%2B%20years%20of%20helping,today%2C%20June%2015%2C%202022.](url)

**Comment by ritwik12** [comment]
RIP IE!!
