### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#2504]
@shiftkey I was thinking that we should enable discussion to our repo for others to discuss stuff without opening up issues.

Repo > Settings > Features section > 
- [x] Discussions

**Comment by shiftkey** [comment]
@ritwik12 done. Let me know if there's anything else that needs to be configured.

**Comment by ritwik12** [comment]
@shiftkey Thanks a lot, that will be all for this :)
