### ISSUE TITLE
Setting up a public write access – as your project does?

### ISSUE THREAD

**Issue by psprint** [up-for-grabs/up-for-grabs.net#2560]
Hi,
I've noticed that [this](https://github.com/up-for-grabs/up-for-grabs.net/new/gh-pages/_data/projects) link allows to create a file for everybody, publicly. Can I ask you in what method did you succeed to configure GitHub like this? I was googling for few hours and didn't find any clues. I would like to create a mob branch in my repository.

**Comment by shiftkey** [comment]
That link doesn't support anyone being able to write to a project, and when you try it in a repository that you don't have write access to you'll see this message as a banner:

> You’re making changes in a project you don’t have write access to. We’ve created a fork of this project for you to commit your proposed changes to. Submitting a change will write it to a new branch in your fork, so you can send a pull request.

That's this part of the URL, and includes the branch name you wish to target: `https://github.com/up-for-grabs/up-for-grabs.net/new/gh-pages`

After that, you can add a path fragment to represent the directory where this file should be created, which is how we end up at `https://github.com/up-for-grabs/up-for-grabs.net/new/gh-pages/_data/projects`

Nothing project-specific, just GitHub guiding people towards forking and opening a PR if they don't have access.

**Comment by ritwik12** [comment]
@psprint What were you looking for exactly?
