### ISSUE TITLE
Github RateLimited

### ISSUE THREAD

**Issue by MaximRouiller** [up-for-grabs/up-for-grabs.net#261]
So... each of us who connect to this page do the request. 

Each time. This lead to my IP being banned from the API as I was making too many of them. 

Of course, I could add my credentials but it wouldn't be very kosher. The API url doesn't take into account that I'm already logged in with Github. Maybe we could have a job that picks them up and generate a JSON file that you could load initially?

Issues doesn't need to be super accurate. A 24 hour update would be plenty IMHO.

Ideas?

**Comment by shiftkey** [comment]
> Issues doesn't need to be super accurate. A 24 hour update would be plenty IMHO.

This should already be occurring: https://github.com/dahlbyk/up-for-grabs.net/blob/gh-pages/javascripts/main.js#L79 And we also defer fetching the issue count until you scroll the item into view

Can you show me in the Chrome Dev Tools what you're seeing after encountering being IP-banned?

**Comment by MaximRouiller** [comment]
Screen cap:

![image](https://cloud.githubusercontent.com/assets/209384/10826166/c98069b2-7e3e-11e5-8d76-2b8208b8f138.png)

**Comment by shiftkey** [comment]
@MaximRouiller sorry, I should have been clearer. What's the response payload from the GitHub API look like?

**Comment by MaximRouiller** [comment]
Main issue is that I had use jspm without an account.

So if I explore the actual response from the server, I get:

``` javascript
{
  "message": "API rate limit exceeded for 204.101.154.3. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by MaximRouiller** [comment]
Corresponding HTTP Response Headers:

``` http
HTTP/1.1 403 Forbidden
Server: GitHub.com
Date: Thu, 29 Oct 2015 17:12:34 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 403 Forbidden
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1446139464
X-GitHub-Media-Type: github.v3
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
Content-Security-Policy: default-src 'none'
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
Content-Encoding: gzip
X-GitHub-Request-Id: CC659A03:7FBA:14FE98F:56325382
```

**Comment by shiftkey** [comment]
> Maybe we could have a job that picks them up and generate a JSON file that you could load initially?

I had thought to host a little web service to wrap this so you're not calling the GitHub API directly (and it has the token), but I have very little spare time to do this at the moment.

**Comment by MaximRouiller** [comment]
Could we define an "up-for-grabs" ;-)

Tell me when you expect as Input and what you expect as Output. 

Maybe it could be statically generated (@daveaglick time to bring Wyam!) JSON files for each YML file you have. I could check if it's something I could do in my spare time. The MVP Summit is coming very soon and I'll have some spare time at night.

**Comment by MaximRouiller** [comment]
The thing is... people are not interested in being 100% in sync with the repository. If we do 1 request per repo per 12/24 hours to generate our file, I think it would be plenty enough to give some excellent feedback for the users.

**Comment by daveaglick** [comment]
If you make fetching whatever data you need part of the static build process, then you could just trigger  the build every N minutes/hours from an Azure web job (see https://gist.github.com/greghaskins/62e30796021e02869240 - there may be other techniques to trigger a Pages rebuild like a dummy commit). The key here would be to make Jekyll go fetch the needed data from GitHub and insert it into the `files` JavaScript array in the generated index.html page. Not sure if Jekyll could handle this though - I'm not that familiar with it's plugin support.

**Comment by MaximRouiller** [comment]
I was more thinking of an Azure WebJob in scheduled mode. The free one of course since we're basically doing nothing with it. 

If you don't have an Azure account, it might as well be a command line app on your machine that updates the repo once in a while. I've checked the Github api and we could technically push the updates to be way shorter if need be. Especially with an authenticated app and conditional HTTP requests.

**Comment by daveaglick** [comment]
Exactly - the nice thing is that if you can get the information as part of the actual Jekyll static build, then all your scheduled job has to do is trigger a Jekyll rebuild from GitHub Pages. That'll keep the logic nice and contained so that when you build locally it works the same way.

**Comment by shiftkey** [comment]
> Could we define an "up-for-grabs" ;-)

I can do a brain dump into a new issue of what I had in mind and then let others chime in there. I'll leave this open until then to remind me.

**Comment by shiftkey** [comment]
Dropping this in here to cross-reference #285 

https://github.com/shiftkey/up-for-grabs-api-demo

**Comment by aph3rson** [comment]
x-refing a comment I made regarding the API quota: https://github.com/up-for-grabs/up-for-grabs.net/issues/567#issuecomment-303563550

**Comment by MaximRouiller** [comment]
Any progress on this?

**Comment by shiftkey** [comment]
@MaximRouiller not really:

 - this needs an infrastructure that we point the browsers at, so they don't get rate-limited by calling GitHub directly
 - the infrastructure either needs to mimic GitHub API calls (pass through) while attaching a authorization token to the request (so it doesn't get rate-limited) or do some sort of aggregation
 - the infrastructure should also cache responses so it too doesn't get rate-limited
 - this needs someone to champion it and own it. I don't have the bandwidth, and I won't speak for the others who are around reviewing PRs to their ability to support this either.

**Comment by shiftkey** [comment]
I think I've got a solution for this ready to go in #1346. If anyone wants to test it out, this is the preview URL: https://deploy-preview-1346--up-for-grabs-test-bench.netlify.com/
