### ISSUE TITLE
Home page form has no button

### ISSUE THREAD

**Issue by atom-box** [up-for-grabs/up-for-grabs.net#2687]
I was expecting there would be a submit button on this form: 
https://up-for-grabs.net
The middle part of the page looks like a form but there is no way to submit.  
Hitting Enter on the keyboard does nothing.

I'm using Firefox (on Kubuntu).   

![upforgrabs-form-buttonless](https://user-images.githubusercontent.com/22874146/115719033-53427c80-a341-11eb-9690-ac7c706ff174.png)

**Comment by SJellen** [comment]
<img width="1002" alt="Screen Shot 2021-04-27 at 12 27 44 PM" src="https://user-images.githubusercontent.com/51421669/116277991-08b36c80-a754-11eb-892e-cd1037d0969b.png">

It's not a form it's three drop downs and when you select an option it filters.

**Comment by ritwik12** [comment]
Thanks @SJellen .
@atom-box We have #2209 that should remove that confusion which you got. Closing this for now.
