### ISSUE TITLE
Figure out how to sort projects in the list

### ISSUE THREAD

**Issue by akoeplinger** [up-for-grabs/up-for-grabs.net#27]
We need to talk about how we sort the projects (e.g. seems a bit unfair that Glimpse is always at the top of the list).

A few possibilites that came to my mind: 
- first-come, first served (as it is now)
- alphabetical
- popularity (might be tough to do)
- random

Thoughts?

**Comment by JakeGinnivan** [comment]
Random would be my pick, or less popular were sorted at the top.

Sent from my Windows Phone

**Comment by dahlbyk** [comment]
Once we have more metadata, I expect the full list to be hidden by default in favor of JS navigation by tag (cloud?). At that point we can do pretty much whatever we want - random feature, recently added (if we capture date), etc.

Looking up stars, issue count, etc. would also be handy, but is trickier without a server-side component.

**Comment by itsjohncs** [comment]
When you click through to a project, then go back in your browser, the list is reshuffled. This makes it unpleasant to browse the list. Storing the seed in a cookie or local storage could solve this, or using a seed that only changes once a day, or encoding the seed in the url? I can code this up if there's some kind of consensus.

**Comment by dahlbyk** [comment]
> When you click through to a project, then go back in your browser, the list is reshuffled. This makes it unpleasant to browse the list.

I'd never noticed that - good point!

> Storing the seed in a cookie or local storage could solve this, or using a seed that only changes once a day, or encoding the seed in the url? I can code this up if there's some kind of consensus.

Throwing a random seen in either `sessionStorage` or a cookie sounds like a good place to start.

**Comment by itsjohncs** [comment]
Sounds good. Apparently you can't seed javascript rng so I just stored the ordering in a list.

**Comment by dahlbyk** [comment]
Seems like this is sufficiently addressed?
