### ISSUE TITLE
CI - test URLs to see they exist

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#277]
As raised in #276 we should check that URLs actually exist. A couple of caveats:
- you can check the structure of all URLs, because relative ones are currently broken
- don't check all URLs, just ones for files that are touched in this PR
- verify both the `site` and `upforgrabs.link`
- redirects are fine, but eventually they should end up at a 200

**Comment by shubheksha** [comment]
Hey, I'd like to work on this. Any ideas regarding how to start?

**Comment by shiftkey** [comment]
@shubhekshajalan sure, here's some quick notes:
- each PR triggers a build on Travis - [config](https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/.travis.yml)
- the current script we run here is validating the schema for a number of fields - [source](https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/scripts/cibuild.rb)
- as a first step, let's verify the values in `site` and `upforgrabs.link` are valid URLs - here's [an example](http://stackoverflow.com/a/7167988/1363815) from StackOverflow

``` ruby
require 'uri'

def valid?(url)
  uri = URI.parse(url)
  uri.kind_of?(URI::HTTP)
rescue URI::InvalidURIError
  false
end
```

**Comment by shiftkey** [comment]
I think we can close this out as #363 should cover it nicely :sparkles:
