### ISSUE TITLE
Improve Logo

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#3026]
Our current logo of Up-for-grabs works great in light mode but it has issues with contrast and visibility under dark mode. We need to find a way to either improve the same logo for dark mode or to use a new and better logo. A logo is something that is the root of some project or product. I wouldn't want to change it without discussions. hence, opening this for discussions on that.
Ref: #3023

**Comment by ghost** [comment]
IMO a new logo would be OK because the current one is a bit complex and somewhat hard to read, but it's not a major deal.

**Comment by Bencourt** [comment]
Hi there, I created a new minimalist logo with a few versions for light/dark mode that I thought might be of some use, and I also made several alternate design sketches if any of those are a better fit. Please let me know if these would be beneficial, and if they are I can create a pull request from my fork that includes the files
![up_for_grabs_logo_white](https://user-images.githubusercontent.com/9601471/160336623-80073447-ffd6-4114-9a49-185b55be555d.svg)
![up_for_grabs_logo_long_blue](https://user-images.githubusercontent.com/9601471/160336648-a6b2fc7b-7494-4d44-b66a-eae821159f27.svg)
![up_for_grabs_logo_black](https://user-images.githubusercontent.com/9601471/160336665-0917d35b-b755-4a4f-8d3c-cb702c8dd150.svg)
![up_for_grabs_logo_ideas](https://user-images.githubusercontent.com/9601471/160336684-8e3253bc-ae69-4abf-bd1c-3ed362725bdf.png)

**Comment by intelkid7** [comment]
Try using a colour which is kinda a mixture of both dark and light shades. For example - sand brown is visible in black as well as white or if you wan't to keep the logo color intact you need to change the logo background

**Comment by Adrian-Samoticha** [comment]
Is there anything that speaks against making an alternative dark-mode version that simply uses a different color palette and [only shows up when dark mode is enabled](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)?

**Comment by chiragkhatri19** [comment]
Can I contribute ?

**Comment by ritwik12** [comment]
@chiragkhatri19 Sure

**Comment by Dani-Google** [comment]
@ritwik12 
Hi 
I want to contribute...

**Comment by chiragkhatri19** [comment]
> @chiragkhatri19 Sure

I'll suggest that we should go for a slight minimal logo, for now there's a lot going in the logo, and as a Beginner in Open Source and stuff, When I visited the website I thought it's some NGO or something. So we should Target the new comers and I can create a Minimal Logo for Up for Grabs. I'll try to make a design layout soon so everyone can agree to that. And then we will change the logo when everyone feels satisfied

**Comment by ritwik12** [comment]
Go ahead please, will wait for your design.

**Comment by chiragkhatri19** [comment]
> Go ahead please, will wait for your design.

I'll create and send you the design by tommorow. So if you like it I can make my First HacktoberFest PR

**Comment by nklansford** [comment]
I'd recommend we make either the existing or new logo an svg so that we can control the colors depending on what mode it is in. I am happy to work on that for the existing logo or help brainstorm a new logo!

**Comment by Ayushbajpai19** [comment]
I cam a really cool logo for this, can you assign me this issue?

**Comment by FlashKoder** [comment]
@ritwik12
Hi I want to contribute and show my designing expertise  here.

**Comment by enricozz** [comment]
Make the logo filled in with white in the center, that way it will be white inside on whatever mode the website is on.

OR

Make the following items white: text, hand border, and stars on the sides.

**Comment by watashiwaaniket** [comment]
Another logo idea: a capsule type design, it can be refined further if wanted.
![upforgrabs](https://user-images.githubusercontent.com/55570910/208253866-3cb5afd1-63ab-4512-9968-f189557379b8.png)
