### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by amsmu** [up-for-grabs/up-for-grabs.net#303]
It is such a long list of projects that scrolling such a long list is annoying. It'll be better to use pagination.

**Comment by shiftkey** [comment]
Agreed. If someone wants to have a go at what this might look like I'm happy to provide feedback or suggestions.

**Comment by qixiaohui** [comment]
Hi, I never commit on open source before, and trying to find my first project to commit, could I work on this issue?

**Comment by shiftkey** [comment]
@qixiaohui I've not heard from anyone else who might be working on it, so you're more than welcome to claim it!

**Comment by qixiaohui** [comment]
Great! Thanks.

**Comment by apoorvnandan** [comment]
I have implemented pagination in the following manner.
- Each page shows only 10 projects
- All the projects (json) are loaded once only as done in the current website so changing pages is quick
- At the bottom of the project list, the site contains page numbers in a horizontal list for navigation with the current page number written in bold
- Rest of the UI remains the same

Here are some screenshots:
![c2](https://cloud.githubusercontent.com/assets/8300539/13820252/7f4ee66a-ebc2-11e5-90b6-0b567a4fbebf.PNG)
![c1](https://cloud.githubusercontent.com/assets/8300539/13820253/7f4f9cc2-ebc2-11e5-8f7e-427e7fd56dd6.PNG)

Is this acceptable?

**Comment by Schavras** [comment]
This issue is still open?

**Comment by dahlbyk** [comment]
Yeah, I don't believe we ever saw a PR from @apoorvnandan. (Perhaps because we never answered "Is this acceptable?" 😊 ) So to answer that question: maybe? I'd have to use it to see for sure, but we would at least want to add Prev/Next links rather than having to pick the correct page to see more.

That being said, I personally feel like I'd prefer an "infinite scroll" approach even if we only render a page's worth of issues initially.

We could also explore having multiple views of the projects - list, cards, graph (link by related tags?), etc - that might make it easier to explore.

**Comment by apoorvnandan** [comment]
I was pretty new to open source projects at that time so I was not sure whether to open a PR or first discuss the changes here. Anyhow, I'll open a PR after adding Prev/Next links. I'll also look into the "infinite scroll" way.
Thanks for replying though. :)

**Comment by dahlbyk** [comment]
> Anyhow, I'll open a PR after adding Prev/Next links. I'll also look into the "infinite scroll" way.

It's :ok: to open a PR now with your progress and [to-dos](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments). Feedback early and often!

**Comment by pajaydev** [comment]
Can I work on this or its completed already??

**Comment by VRamazing** [comment]
Hi there!!! is this issue still open

**Comment by andy5995** [comment]
@VRamazing I see that PR #727 was submitted 10 days ago, but it hasn't been reviewed yet.

**Comment by dslivka1** [comment]
Hi guys ! Still open ? I could do it.

**Comment by ritwik12** [comment]
@dslivka1 Yes it is open, I will close this once we'll get a working PR.

**Comment by Zarad1993** [comment]
Hi guys, is this being worked on?

**Comment by ritwik12** [comment]
@Zarad1993 No one in our knowledge. Got few PRs but closed due to lack of proper working. you may go on with this. But please have a look at previous PRs too. It will help you.

**Comment by ritwik12** [comment]
Closing this as #665 exists for the same and no work is being done on this.
