### ISSUE TITLE
Save dark mode in local storage

### ISSUE THREAD

**Issue by developer-diganta** [up-for-grabs/up-for-grabs.net#3044]
The dark mode once enabled/disabled can be stored in local storage for future reference so that the next it automatically loads in the previous mode?

**Comment by ritwik12** [comment]
@developer-diganta Yep, that would also remove the confusion that we have to make DARK or LIGHT default as per @connorahern in #3023.

Want to do it @developer-diganta? let us know if any help needed.

**Comment by developer-diganta** [comment]
Yes, I'll do it then!
