### ISSUE TITLE
Fill out missing data

### ISSUE THREAD

**Issue by dahlbyk** [up-for-grabs/up-for-grabs.net#31]
Now that #17 has been addressed, we need to fill in missing project descriptions/tags.

**Comment by mexx** [comment]
Done with #37 -> :ok_hand:

**Comment by xavierdecoster** [comment]
Done with #40

**Comment by ovatsus** [comment]
Done with #41

**Comment by analogrelay** [comment]
Submitted #47 but want to get @jeffhand's sign off first.

**Comment by ploeh** [comment]
Done with #42, #43, and #44

**Comment by nulltoken** [comment]
@dahlbyk :+1: :heavy_plus_sign: :heart:

**Comment by thecodejunkie** [comment]
Fixed Nancy with #53
