### ISSUE TITLE
Filter by tag

### ISSUE THREAD

**Issue by dahlbyk** [up-for-grabs/up-for-grabs.net#32]
We have tags now - let's support filtering by them!

I can't shake the thought that some sort of tag cloud would be neat, though that's certainly not a requirement. Or it could be added later. Along with dozens of other visualizations of the included projects! But I digress...

Random thoughts:
- As @akoeplinger mentioned [here](https://github.com/dahlbyk/up-for-grabs.net/pull/29#discussion_r7879552), Jekyll can render the projects as JSON so we don't have to parse the HTML.
- Filtering by a tag should probably count as a navigation event and be permalinkable.
- Should we support multiple tag filters? AND or OR?
- Filtering by special characters, e.g. `F#`, should work.

**Comment by shiftkey** [comment]
> Filtering by a tag should probably count as a navigation event and be permalinkable.

+:100: to making it permalinkable

> Should we support multiple tag filters? AND or OR?

:thumbsup: - use OR because the sample of projects we have at the moment is so small (lol webscale)

> Filtering by special characters, e.g. F#, should work.

:thumbsup:

**Comment by akoeplinger** [comment]
I guess this can be closed now?

**Comment by dahlbyk** [comment]
> I guess this can be closed now?

Yes!
