### ISSUE TITLE
Tutorial to beginners

### ISSUE THREAD

**Issue by JAGDF** [up-for-grabs/up-for-grabs.net#3549]
I am new to this repository and don't have knowledge of GitHub
 I can't add any pull request right now. May someone teach me how?

**Comment by LyndaLilly** [comment]
I am new to GitHub. Can someone tell me how it works. Thank you

**Comment by vatsalasharma04** [comment]
github is mainly an open source platform. used for supporting, helping and sharing our knowledge with our peers. if you are new to github the most less you can do is first create a repo and then add any code you have written. go to your profile icon on right hand side . click on it . go to your repository. , click on create a new repo. write a name for your repo. make it public or private its your choice. click on create rpository. click on upload file and select fiole from your comp. then click on commit changes.
thus you would have been uploading your first code on github.
if you find this helpful. please tell me.

**Comment by LariDsSantos** [comment]
Hello guys! I'm new to GitHub too and it's very nice meet a platform like this, where have a lot of people sharing knowledge!

I wish a good experience for all.

**Comment by LariDsSantos** [comment]
> github is mainly an open source platform. used for supporting, helping and sharing our knowledge with our peers. if you are new to github the most less you can do is first create a repo and then add any code you have written. go to your profile icon on right hand side . click on it . go to your repository. , click on create a new repo. write a name for your repo. make it public or private its your choice. click on create rpository. click on upload file and select fiole from your comp. then click on commit changes. thus you would have been uploading your first code on github. if you find this helpful. please tell me.

>> Thanks for the tips!

**Comment by abhra2020-smart** [comment]
You click the pencil, edit the file, and then create the PR (pull request).

**Comment by JAGDF** [comment]
Problem solved.
