### ISSUE TITLE
Improving Card Tags

### ISSUE THREAD

**Issue by Yasir761** [up-for-grabs/up-for-grabs.net#3605]
![Issue - 1](https://user-images.githubusercontent.com/74600745/201686217-24c96e0d-0c96-40d5-8ee7-92fd21f82afd.PNG)
Cards Tags should be at the bottom. This means whether the content of the card is  small or big, card tags are positioned at the bottom.

**Comment by ramialkarshi** [comment]
مرحبا ياسر

**Comment by aruadecarvalho** [comment]
Hi! Can I work on this issue?

**Comment by SaintQ969** [comment]
Hello, I would love to work on this if you don't mind?

**Comment by sh471** [comment]
Sure, it sounds great.

*Best Regards,*

*Sherif Hikal*

**Comment by SaintQ969** [comment]
Thank you so much for the opportunity.
Is there a way I can mail you directly?

**Comment by Yasir761** [comment]
Since I'm not a Maintainer of this repo so, I cannot assign this to anyone. I also want to work on this issue that's why I raised it
@aruadecarvalho

**Comment by Yasir761** [comment]
@SaintQ969 @aruadecarvalho I cannot assign it to anyone of you because I am not an owner of this repo.

**Comment by Momo1kz** [comment]
é&²zkk
@ebekker

**Comment by sh471** [comment]
> Thank you so much for the opportunity. Is there a way I can mail you directly?

Absolutely, thank you for reaching out.

**Comment by Momo1kz** [comment]
@camilosampedro fg

**Comment by Memomer** [comment]
Can i work on this issue?

**Comment by Upendra672** [comment]
I would love to work on this issue if you don't mind

**Comment by sh471** [comment]
> Can i work on this issue?

**Comment by luuu-xu** [comment]
Hi, is someone still working on this issue? I'd love to work on it if nobody is.

**Comment by RachitSahu26** [comment]
don't ask that can i do this. if you can do then do

> Can i work on this issue?

**Comment by aditya-desai-19** [comment]
I would like to work on this. Please assign this issue to me.

**Comment by sh471** [comment]
Absolutely, go ahead.


*Best Regards,*

*Sherif Hikal*

**Comment by shiftkey** [comment]
Resolved via #4283
