### ISSUE TITLE
Feature Request - Fork Count

### ISSUE THREAD

**Issue by divyab275** [up-for-grabs/up-for-grabs.net#3617]
Hello,

I was using Up For Grabs, and thought it would be nice if there was a fork count along with repo name. 

Why?
It gives me an idea of how big the project is before opening the link.

I was thinking something like this, but definitely more cleaner!
![image](https://user-images.githubusercontent.com/22278173/202866374-6ca55f95-a356-4c49-9483-93d3fd4ae359.png)

**Comment by alex-barrios** [comment]
Hi @divyab275! Can I work on this issue?

**Comment by nenaqui** [comment]
Hola, puedo trabajar en este tema igual

**Comment by ritwik12** [comment]
@divyab275 Thanks for opening up this. This would be a good addition. We can also include Starred with Fork.

**Comment by ritwik12** [comment]
@alex-barrios If @divyab275 is not working on this, Feel free to.

**Comment by alex-barrios** [comment]
Sounds good @ritwik12! I have started to work on it because I do not think @divyab275 is working on it.

**Comment by brunoocaranza** [comment]
Hi please i Need help

**Comment by XxCarlxX** [comment]
Yes I'm here, 💯C J. Murray On 6/12/2022 20:33, brunoocaranza ***@***.***> wrote:
Hi please i Need help

**Comment by Irish78** [comment]
>

Yes

**Comment by Irish78** [comment]
> Hi @divyab275! Can I work on this issue?

Yes

**Comment by Irish78** [comment]
> @divyab275 Thanks for opening up this. This would be a good addition. We can also include Starred with Fork.

**Comment by joseearias** [comment]
Hi! Seeing as it's been months since an update can I have a go at this issue?

**Comment by ritwik12** [comment]
Yeah sure

**Comment by vansharora03** [comment]
Is @joseearias still working on this? If not I can give it a go!

**Comment by shiftkey** [comment]
Closing this out as this is now available on the site with https://github.com/up-for-grabs/up-for-grabs.net/pull/4014 - refinements or additional ideas welcome!

**Comment by axcheiste-rooney-mara** [comment]
Is there a good damn issue
