### ISSUE TITLE
Domain name is not accessible - possible problem?

### ISSUE THREAD

**Issue by enricozz** [up-for-grabs/up-for-grabs.net#3625]
The hyphens in the domain name aren't good for SEO and aren't accessible. upforgrabs.net, for example, would be much better.

**Comment by ritwik12** [comment]
@ashe-not Thanks for pointing this out. I am not that much into SEO. @shiftkey might be able to comment on it.

**Comment by patel-aum** [comment]
now the site is appearing first in the search results.

**Comment by camerondevuk** [comment]
just get a real domain fr

**Comment by camerondevuk** [comment]
Hey there, I work in seo do you need help with anything?

Thanks,
Cameron
