### ISSUE TITLE
Meta Description & Open Graph

### ISSUE THREAD

**Issue by dahlbyk** [up-for-grabs/up-for-grabs.net#364]
What a spectacularly lame embed!
<img width="172" alt="slack_2016-02-17_23-47-04" src="https://cloud.githubusercontent.com/assets/133987/13134900/fcd53b5a-d5d0-11e5-8812-bd202631c8fa.png">

Would be awesome if someone with HTML skills and some good words could fix this.
- [x] Add a `<meta name="description" .../>` with good words

Bonus:
- [x] Add [Open Graph markup](https://developers.facebook.com/docs/sharing/webmasters#markup) with good words/URLs

**Comment by hobbyexplorer** [comment]
Hi @dahlbyk, 
I would like to work on this issue.

**Comment by dahlbyk** [comment]
Much better, thanks @magevadi!
<img width="408" alt="slack_2016-02-22_16-32-29" src="https://cloud.githubusercontent.com/assets/133987/13235129/54a66824-d98a-11e5-9fb2-831db0308332.png">
