### ISSUE TITLE
#paid

### ISSUE THREAD

**Issue by Irish78** [up-for-grabs/up-for-grabs.net#3703]
Home
SDK
Dev Guide
Reference
Resources
Videos
Blog
Android.com
	Search
Community
Developer Forums
IRC, Twitter
Technical Articles
List of Articles
Tutorials
Hello World
Hello Views
Hello Localization
Hello Testing
Notepad Tutorial
Activity Testing
Sample Code
Getting the Samples
List of Samples
More
Common Tasks
Troubleshooting Tips
FAQs
 
IRC and Twitter
In addition to the Android developer forums, you can participate in the Android developer community through IRC and you can follow us on Twitter.

IRC
Several IRC channels are available for discussions about developing Android applications.

Channel	Host	Description
#android	irc.freenode.net	General discussion about Android (and Android development).
#android-dev	irc.freenode.net	Discussion focused on developing Android apps.
If you haven't used IRC before, check http://en.wikipedia.org/wiki/List_of_IRC_clients » for a helpful list of IRC clients. Alternatively, you could also use this web interface », which does not require any installation, to join discussions on the Android IRC channels.

Here are some tips for using IRC:

Set your nickname before you join the channel.
Registering your nickname prevents others from using your nickname or impersonating you later:
/nick <yournickname>
/msg nickserv register <password> <email>
Afterwards, when you connect, you'll need to supply a password:

/connect irc.freenode.net
/nick <yournickname>
/msg nickserv identify <password>
/join #android-dev
Twitter
You can follow us on Twitter at this account:

http://twitter.com/androiddev

↑ Go to top
Except as noted, this content is licensed under Creative Commons Attribution 2.5. For details and restrictions, see the Content License.
Site Terms of Service - Privacy Policy - Brand Guidelines

**Comment by bingchris** [comment]
bro wrote a essay
