### ISSUE TITLE
www.up-for-grabs.net is not redirecting to up-for-grabs.net Possible problem?

### ISSUE THREAD

**Issue by MahendraShiyal** [up-for-grabs/up-for-grabs.net#3932]
www.up-for-grabs.net is not redireting to up-for-grabs.net

Maybe it's an issue with redirecting itself. not so sure about it. 

==>Screenshot<==

![image](https://user-images.githubusercontent.com/126650948/235900277-8629745a-6702-449b-a01e-828033965b1d.png)

**Comment by msaad7777** [comment]
I want to contribute to this project, can I have any issue assigned ?

**Comment by Heiteinany18** [comment]
I want to contribute, can you  assign issue to me.

**Comment by Randall042251** [comment]
i believe i can help with this issue

**Comment by shiftkey** [comment]
I can't spot anything obviously wrong with the `www.` redirect so I'm going to close this out as resolved:

```
> curl -I www.up-for-grabs.net
HTTP/1.1 301 Moved Permanently
Date: Mon, 19 Jun 2023 13:36:09 GMT
Connection: keep-alive
Location: http://up-for-grabs.net/
X-Served-By: Namecheap URL Forward
Server: namecheap-nginx
```

The "taking too long to respond" issue from `up-for-grabs.net` is a different topic, and I'd recommend starting a fresh discussion about that in a new issue if anyone else spots this and can troubleshoot further.
