### ISSUE TITLE
Sending high traffic?

### ISSUE THREAD

**Issue by franciscop** [up-for-grabs/up-for-grabs.net#395]
Hi, I love up-for-grabs and I've been trying to make my project [as friendly to it as possible](https://github.com/umbrellajs/umbrella/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aup-for-grabs), creating, documenting and helping in several issues. It takes a bit more of effort to handle an up-for-grabs issue than doing it myself, but in exchange I get a lot of satisfaction helping new people in OSS.

My question is simply though and [it's about this specific issue](https://github.com/umbrellajs/umbrella/issues/52). **How do you decide what projects to show in up-for grabs?** Three people stated wanting to do the issue, which it seems a lot, considering that probably 10x or more people saw the issue and didn't say anything. Is this normal or based on anything like previous solved issues?

I am also not sure what to do, since they are all probably starting and I want to keep them motivated. So a "first to pull" rule would make it unfair for people with questions that already committed some time, but a "first to comment" makes it unfair for people who join later the conversation. Could you also recommend something here?

**Comment by dahlbyk** [comment]
> Hi, I love up-for-grabs and I've been trying to make my project as friendly to it as possible, creating, documenting and helping in several issues. It takes a bit more of effort to handle an up-for-grabs issue than doing it myself, but in exchange I get a lot of satisfaction helping new people in OSS.

Awesome! That's exactly why we're here!

> How do you decide what projects to show in up-for grabs? Three people stated wanting to do the issue, which it seems a lot, considering that probably 10x or more people saw the issue and didn't say anything. Is this normal or based on anything like previous solved issues?

The order in which projects are shown in [randomized per session](https://github.com/up-for-grabs/up-for-grabs.net/pull/110), so it may just be random luck that several new people ended up looking at the same issue? Maybe there's something particularly approachable about your project ("tiny")? You could always ask the three people who converged on that issue. :grinning: 

> I am also not sure what to do, since they are all probably starting and I want to keep them motivated. So a "first to pull" rule would make it unfair for people with questions that already committed some time, but a "first to comment" makes it unfair for people who join later the conversation. Could you also recommend something here?

I wouldn't worry so much about being "fair," just be open in your communication and encourage the same from everyone else. Ultimately the goal is to merge some code, so an open PR is a pretty strong claim. An active PR is even better. An active PR that's close to mergeable, better still. Until you have the contribution you're looking for, all you can do is encourage anyone who is interested to participate—by discussing pre-PR, by reviewing an open PR, by picking up a PR that has gone stale.

If someone _does_ appear to have lost interest in an open PR, try to keep them in the loop ("FYI, @dahlbyk, @franciscop plans to pick up where this PR left off.") until they opt out.

---

I'm sure others with different OSS experiences will have a different perspective.

**Comment by franciscop** [comment]
Awesome, thanks for the tips
