### ISSUE TITLE
consider adding a pull request template 

### ISSUE THREAD

**Issue by repo-reviews** [up-for-grabs/up-for-grabs.net#3995]
Hi, nice work!

Consider adding a pull request template to `.github/PULL_REQUEST_TEMPLATE.md` that references your contribution guidelines:

https://github.com/repo-reviews/repo-reviews.github.io/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by techmannih** [comment]
hello @repo-reviews ,
I want handle this issue .... please assign me
