### ISSUE TITLE
Wrong information in axelrod.yml

### ISSUE THREAD

**Issue by raphaelm** [up-for-grabs/up-for-grabs.net#412]
Somehow, in https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/axelrod.yml, @drvinceknight forgot to replace the description of pretix.yml with the description of axelrod ;) While I'm not at all unhappy with people finding pretix more easily, I guess this is not intended. :)

**Comment by drvinceknight** [comment]
Much appreciated! Not sure how that happened. Will take a look :)

**Comment by shiftkey** [comment]
Nice spot. I will happily accept a PR to update it.

**Comment by drvinceknight** [comment]
Thanks: https://github.com/up-for-grabs/up-for-grabs.net/pull/414

:) 👍
