### ISSUE TITLE
Add tooltip for fork numbers

### ISSUE THREAD

**Issue by koppor** [up-for-grabs/up-for-grabs.net#4303]
When browsing the up-for-grabs web site, one sees a pull request icon and a number after it. It is not clear, what this number means.

Propposal: Add a tool tip on hover (and maybe keep the mouse pointer as pointer - and not change it to a text cursor)

![image](https://github.com/up-for-grabs/up-for-grabs.net/assets/1366654/f4e09207-2449-4390-85bc-e804b10b9956)

**Comment by PushpRatan** [comment]
I have fixed this issue, this is my first contribution. Please guide me if something is wrong. Thank you.

**Comment by llr3v0ll** [comment]
I've opened a pull request for this issue
