### ISSUE TITLE
Bug: Fork svg color in dark mode

### ISSUE THREAD

**Issue by mrical** [up-for-grabs/up-for-grabs.net#4312]
In the dark mode, the fill color of the fork SVG does not change to a suitable color, making it hard to see. This affects the user experience in dark mode.

Screenshot of the current behaviour

<img width="919" alt="dTnPYhJezx" src="https://github.com/up-for-grabs/up-for-grabs.net/assets/60258119/e096df4e-9630-4c04-95d6-03af7a0c27cf">

Screenshot of the proposed behaviour

<img width="941" alt="chrome_78PCznijim" src="https://github.com/up-for-grabs/up-for-grabs.net/assets/60258119/0445b42e-7640-40f9-90a0-3aa439169b3c">

**Comment by mrical** [comment]
Hello, you can assign this issue to me, I am sure I can fix this issue

**Comment by onyangoju** [comment]
svg {
  fill: currentColor;
  color: dark;
}
  
svg:hover {
  color: white;
}

**Comment by mrical** [comment]
@onyangoju I have not proposed for change in hover state, color of fork (i.e. black) in dark mode itself is not suitable

**Comment by shiftkey** [comment]
This was fixed in [#4337](https://github.com/up-for-grabs/up-for-grabs.net/pull/4337)
