### ISSUE TITLE
@06b How can one change dark mode from keyboard with this? Which buttons?

### ISSUE THREAD

**Issue by CAOnees** [up-for-grabs/up-for-grabs.net#4355]
@06b How can one change dark mode from keyboard with this? Which buttons?

_Originally posted by @ritwik12 in https://github.com/up-for-grabs/up-for-grabs.net/issues/3526#issuecomment-1357498095_

**Comment by ftTesb** [comment]
في الثلاثاء، ٢٨ نوفمبر ٢٠٢٣ ٣:٠٥ ص C∆ ***@***.***> كتب:
