### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by Mayankkatheriya** [up-for-grabs/up-for-grabs.net#4489]
![image](https://github.com/up-for-grabs/up-for-grabs.net/assets/128832286/0e247423-1683-46b6-80ad-3138356272af)

it becomes more attractive if we add some hove effect on these div
like on hover its scale becomes larger and box shadow increase to give 3D like structure

**Comment by Kamainkokamain** [comment]
Bouruoree

**Comment by Mayankkatheriya** [comment]
What?

**Comment by mukhammadjcn** [comment]
Hi, there how can I send my version to you

**Comment by shiftkey** [comment]
Resolved via https://github.com/up-for-grabs/up-for-grabs.net/pull/4513
