### ISSUE TITLE
Wrong files showing while querying the index path using lucene.

### ISSUE THREAD

**Issue by Panda-Srujan** [up-for-grabs/up-for-grabs.net#449]
Hi everyone,

I'm new to Lucene. I've an issue while querying the index file (path) while searching for a string in the files (say: doc files). I've looped through all the files using the following code.

```
string indexFileLocation = txtRootDirectory.Text.Trim();
            Lucene.Net.Store.Directory dir = Lucene.Net.Store.FSDirectory.GetDirectory(indexFileLocation,
                 false);
            Lucene.Net.Search.IndexSearcher searcher = new Lucene.Net.Search.IndexSearcher(dir, false);
            Lucene.Net.Index.Term searchTerm = new Lucene.Net.Index.Term("content", 
                 txtSearch.Text.Trim());
            Lucene.Net.Search.Query query = new Lucene.Net.Search.TermQuery(searchTerm);
            Lucene.Net.Search.Hits hits = searcher.Search(query);

for (int i = 0; i < hits.Length(); i++)
            {
                Lucene.Net.Documents.Document doc = hits.Doc(i);
                StringBuilder contentValue = new StringBuilder();
                contentValue.Append(doc.Get("content"));
                string id = doc.Get("id");
                lblSearchResults.Text += id + "<br />";
            }
```

But unfortunately, I've been getting the same search results, the same file name as follows.

![repetition](https://cloud.githubusercontent.com/assets/16679478/18156642/5752f1e0-7035-11e6-8074-6c30a1c3f2f6.PNG)

I couldn't figure out if I'm doing wrong anywhere in my code. Please help me out.

Thanks in advance.

**Comment by shiftkey** [comment]
I'm not sure this is the right place to ask - maybe [StackOverflow](http://stackoverflow.com/questions/tagged/lucene.net)?
