### ISSUE TITLE
setup codespell to avoid more typos

### ISSUE THREAD

**Issue by RayBB** [up-for-grabs/up-for-grabs.net#4555]
There are currently tons of typos in this project. Someone should fix them.
Then setup codespell spell to check for them each time there is a pr 👍 

https://github.com/codespell-project/codespell

<img width="504" alt="image" src="https://github.com/up-for-grabs/up-for-grabs.net/assets/921217/e4a21614-56d5-4945-b534-42a765e65cf5">

**Comment by aroramrinaal** [comment]
I'd like to help out with fixing the typos in the project. I'll also set up Codespell Spell to catch them in future pull requests. I don't know Codespell yet, but I'm eager to learn on the go.

Could you please assign this issue to me?

**Comment by RayBB** [comment]
@aroramrinaal you are assigned now.

**Comment by aroramrinaal** [comment]
@RayBB I was thinking of integrating codespell into the project by adding a script to run codespell checks, configuring it to scan for spelling mistakes, and setting it up to automatically execute within the CI/CD pipeline on each pull request.

Am I in the right direction?

**Comment by RayBB** [comment]
@aroramrinaal 
I'm not a maintainer of this project but that sounds about right to me. You probably will need a separate PR first to fix all of the typos that you can. Then you will need to add documentation for how to add exceptions for code spell when a word is spelt right but they think it's wrong (usually technical names).

**Comment by tomkoevoets** [comment]
hey there,

I'm a first year student in it and need to make a small bigger contribution to an open source project.
is there anybody that can help me on my way with this since its my first time and I'm reasonably unexperienced in programming.

thanks in advance,

Tom

**Comment by RayBB** [comment]
@tomkoevoets there is already a PR open for this change so you'll have to find another issue 👍 
https://github.com/up-for-grabs/up-for-grabs.net/pull/4562
