### ISSUE TITLE
images/line.png not found

### ISSUE THREAD

**Issue by ckhatri** [up-for-grabs/up-for-grabs.net#486]
Whenever I try doing docker compose I get hit with 
ERROR `/images/line.png' not found.

I found the issue is in stylesheet.css

```
  a.main, a:hover, .as-link.main, .as-link:hover {
    color: #2E7BA9;
    background-image: url(/images/line.png);
    background-repeat: repeat-x;
    background-position: left bottom; }
```

Not sure if line should be an actual file or if this is a typo. Thought I'd bring it up to people's attention!

Hope I did this issue stuff right. It's my first time.

**Comment by shiftkey** [comment]
Introduced here: https://github.com/up-for-grabs/up-for-grabs.net/commit/f8dba3d8a39a9dafadd26ae6d164d21b9f378e4f#diff-b8b01588d730dbc5770b98a7f4a45687R286

@daveaglick thoughts?

**Comment by dahlbyk** [comment]
I'm inclined to remove the three `background-*` declarations - the existing link underline seems adequate to me.

@ckhatri how do you feel about closing your first issue with your first pull request? 😀

**Comment by ckhatri** [comment]
yes please! just passed travis CI too, should be good to go.

**Comment by daveaglick** [comment]
Oh man, totally missed the notification on this one. I'm sure it was just a mistake/typo. Glad it got resolved! If it looks good, :shipit:

**Comment by daveaglick** [comment]
@ckhatri Congrats on your first PR!
