### ISSUE TITLE
Visiting the site with javascript disabled does not display any projects

### ISSUE THREAD

**Issue by Hestben** [up-for-grabs/up-for-grabs.net#511]
Hey!

I just wanted you to know, that if I visit the site ([link](http://up-for-grabs.net/#/)) with javascript disabled, only the static content is displayed, no projects are listed, and no message informing the user that the site requires javascript is displayed.

This could be useful, whenever a user of noscript visits the site.

**Comment by shiftkey** [comment]
@Hestben good point. If someone wants to take a shot at this, I'd be happy to give some ideas.

**Comment by arjunnn** [comment]
Hi, I want to help.  Please give me some pointers. Maybe a `<noscript>`?

**Comment by waldyrious** [comment]
(Disclaimer: I haven't looked in detail at the current setup, I don't know much about using Jekyll)

Could we tell Jekyll to generate a static page listing all the contents of the _data/projects folder, and then progressively enhance it via javascript, to inject a search field and hide blocks whose tags ([or title](https://github.com/up-for-grabs/up-for-grabs.net/issues/512)) don't match the search query?

**Comment by shiftkey** [comment]
A `<noscript>` tag on the home page would be a good first go at this.

As to statically generating the markup for each project, this is how we're generating the JSON for the projects (`jsonify` is included by default in Jekyll):

https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_includes/scripts.html#L47

The rest of this file is the templates that get rendered. I'm a bit hazy on how it all hangs together, due to it being so long since I've been in there, but I gather that's what you'd like to recreate as static markup.

You can have a read about how Jekyll manages data files here: http://jekyllrb.com/docs/datafiles/

**Comment by waldyrious** [comment]
Thanks for the pointers! Unfortunately I can't promise I'll have the availability to work on this anytime soon, but hopefully others can :)

**Comment by psanjay-1** [comment]
can i work on this issue?

**Comment by 0x006E** [comment]
Is this now also open? I want to contribute

**Comment by conner-calhoun** [comment]
I added a noscript tag that displays a banner similar to the one found at the top of the page. How could I go about pushing my code?
![image](https://user-images.githubusercontent.com/18505623/30121016-702fd444-92f8-11e7-9100-cf0661e9df41.png)

**Comment by shiftkey** [comment]
@callium if you can find the file in the repository that you need to update, you can [edit the file](https://help.github.com/articles/editing-files-in-another-user-s-repository/) in the web editor which will open a pull request for review.

**Comment by mrtnmgs** [comment]
Hi @shiftkey I tried fixing this issue a few months ago but got confused and dropped it. I'm back at it now! One issue I'm having is that the tests fail with this error: `Unknown operator forloop in index.html`. But `forloop` works and is documented here: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#helper-variables
Shall I not use it for some reason? Or maybe the tests need an update? Thanks for your help!

**Comment by shiftkey** [comment]
@mrtnmgs my best guess is that GitHub Pages probably doesn't support everything in the Liquid syntax

**Comment by mrtnmgs** [comment]
I guess that makes sense! @shiftkey Thanks, I'll find a way around it...
