### ISSUE TITLE
Use project names in search, not just tags

### ISSUE THREAD

**Issue by waldyrious** [up-for-grabs/up-for-grabs.net#512]
Otherwise we have to include the project name as a tag so that users can find them, which is kind of a hack.

**Comment by shiftkey** [comment]
This might be a silly question from me, but if you already know the name of the project why wouldn't you go straight to Google/GitHub to find it?

**Comment by waldyrious** [comment]
As a curious technically-minded person, or enthusiastic user but not yet involved in development, I might know about a project and want to get involved, but since they don't necessarily use the same ways to identify easy/beginner issues (different bug trackers, different label names, sometimes even manually curated lists rather than query results in an issue tracker, etc.), I would like to be able to use a resource like up-for-grabs to seek that information in a convenient way. Removing barriers is good for anyone, but especially important for newcomers :)

**Comment by dahlbyk** [comment]
I wouldn't object to this, e.g. a React search could find the React project in addition to projects related to it.

**Comment by ahuwaa** [comment]
Going to take a shot at this unless o.w. told not to

**Comment by waldyrious** [comment]
@shiftkey with the merging of #534, I suppose this could be closed, right? I tried to test it but I'm hitting #594.

**Comment by shiftkey** [comment]
@waldyrious I guess we can't close this out just yet. I've left a note in #534 to see if we can get to the bottom of it...

**Comment by shiftkey** [comment]
Closing this out to get things off my plate.

@waldyrious if you would like to revisit this there's some details in #594 around what might have been the problem.
