### ISSUE TITLE
Topics, the latest github update

### ISSUE THREAD

**Issue by fronchetti** [up-for-grabs/up-for-grabs.net#544]
Have you seen what GitHub has just released? Topics, a new tool that can be very useful for this project.

>  Topics are labels that create subject-based connections between GitHub repositories and let you explore projects by type, technology, and more.

What do you think about including the topics on the website?

https://github.com/blog/2309-introducing-topics (Blog)
https://help.github.com/articles/about-topics/ (Documentation)

![02b5bfb2-e7ab-11e6-8499-33d33c240621](https://cloud.githubusercontent.com/assets/15092904/22489656/e9ad84be-e7ff-11e6-949f-b17c3251713b.png)

**Comment by fronchetti** [comment]
They follow the same logic as the tags available in the .yml file. :thumbsup:

**Comment by shiftkey** [comment]
@fronchetti it would require deeper GitHub information to automagically generate them, and I don't see it being available from the GitHub API currently...

**Comment by dahlbyk** [comment]
Once available from the API, we could provide a utility to create/update a project file given a GitHub project: `up-for-grabs dahlbyk/posh-git`

**Comment by shiftkey** [comment]
I'm gonna close this out to tidy things up a bit, but feel free to comment once it's available from the API and we can figure out how that fits with Up for Grabs.
