### ISSUE TITLE
Remove the BugNET project, as it appears to be dead?

### ISSUE THREAD

**Issue by bigwave** [up-for-grabs/up-for-grabs.net#548]
[BugNET ](https://github.com/dubeaud/bugnet) appears to be dead, there are 114 open issues, 4 outstanding pull requests and the last commit was April 2016

And this [comment](https://github.com/dubeaud/bugnet/issues/235#issuecomment-268624982) says "The developer of BugNET has ceased supporting it."

Remove this project from up-for-grabs?

**Comment by shiftkey** [comment]
@bigwave :thumbsup:

**Comment by feliperomero3** [comment]
@bigwave the author of BugNET @dubeaud did a couple of commits on Feb 24, 2017. Just saying, don't be too quick on assuming is a dead project. I thought this whole thing of "up-for-grabs" movement was all about being a welcoming community. My two cents.

**Comment by shiftkey** [comment]
>  Just saying, don't be too quick on assuming is a dead project. 

If the maintainer isn't interested in working with new contributors, I don't really see the point of listing the project here.
