### ISSUE TITLE
A logo would be cool

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#55]

**Comment by akanshgulati** [comment]
Sir I have made a logo for up-for-grabs in which I have tried to add site name in the logo. I have used up arrow to show "up", and added F for "for" and G simultaneously. The ideology is simple that site will reach high goals and will improve with time (Up-arrow signify that). Given small twist to letter "U" too. Hope you like it.

![up-for-grabs-logo](https://f.cloud.github.com/assets/5287100/2259648/88b879d0-9e37-11e3-9422-14a8f9b87fa7.png)

**Comment by hnrkndrssn** [comment]
The first thing I thought of when looking at the name, up-for-grabs, was one of these
![image](https://f.cloud.github.com/assets/1035315/2275316/9aa5f312-9f26-11e3-9e2a-6989d22309c8.png)

So I took that, and :recycle: the U from @akanshgulati logo up top, adding an up-arrow to it and got this
![image](https://f.cloud.github.com/assets/1035315/2275298/5dd161ba-9f26-11e3-9aee-f6bdc04751bd.png)

Then I thought, it's a bit big and unwieldy, so I joined the two objects together and got this
![image](https://f.cloud.github.com/assets/1035315/2275339/e3b6fc9a-9f26-11e3-88d6-2d7d2977e9cd.png)

But then my mind wandered, and thought of Dinosaurs, and who doesn't like dinosaurs...so, introducing the Upforgrabsiosaurus
![image](https://f.cloud.github.com/assets/1035315/2275367/2154a66a-9f27-11e3-8e4e-dc740fbedd35.png)

They probably need some more :lipstick: (they were done in Paint.net), but I :pray: that it might be something you guys would consider using :relaxed: otherwise just :put_litter_in_its_place: :sob:

**Comment by adamralph** [comment]
lol at the dinosaur!

**Comment by shiftkey** [comment]
Found myself cruising The Noun Project a bit, and this icon stood out:

https://thenounproject.com/term/network/126074/

![screen shot 2015-04-02 at 3 32 14 pm](https://cloud.githubusercontent.com/assets/359239/6964878/7bf615fc-d94d-11e4-82dd-79dfe9e4fb5f.png)

https://thenounproject.com/term/team/125795/

![screen shot 2015-04-02 at 3 32 19 pm](https://cloud.githubusercontent.com/assets/359239/6964877/7bf4794a-d94d-11e4-9a4b-dc74d4b225ed.png)

**Comment by ChrisMissal** [comment]
+1 @shiftkey – and for activating this issue again :)

**Comment by jannikanker** [comment]
How about a logo that combines an upload icon (like https://thenounproject.com/term/upload/61791 ) and a "grabbing" hand (like this: https://thenounproject.com/term/closed-hand/101204 ) ? I'm not a graphics expert by any means and I do see a possible "misinterpretation" of this example, but maybe someone with actual skills might be able to make a non-controversial version, hehe?

![upforgrabs1](https://cloud.githubusercontent.com/assets/1769849/9437816/76401784-4a59-11e5-90bf-369de575b71f.png)

**Comment by pertrai1** [comment]
@akanshgulati +1 on the logo

**Comment by shiftkey** [comment]
While I love the enthusiasm and suggestions here, I think I'm going to organize for a 99designs contest to see if we can finally close this out.

I'm happy to stump up the money for it, and I'll drop some info in here as I'm setting up the details (I've not done this before, so if you have any tips it'd be :heart:). Hopefully I can get it going this week, but I'm currently digging my way out from three weeks of stuff so that's very optimistic.

cc @dahlbyk @jrusbatch

**Comment by hnrkndrssn** [comment]
I quite liked this one https://thenounproject.com/search/?q=collaboration&i=176341

**Comment by una** [comment]
thoughts: 
![img_5542](https://cloud.githubusercontent.com/assets/1693164/10545195/148ecf04-73ed-11e5-81c7-433fa979c567.JPG)

sorry it got rotated :/

**Comment by ChrisMissal** [comment]
I really like these @una! This one's my favorite:

![image](https://cloud.githubusercontent.com/assets/67798/10545785/006dda1c-73f0-11e5-935f-f56d2858d2cf.png)

**Comment by augustoproiete** [comment]
+1 @una first logo

**Comment by adamralph** [comment]
My tuppence worth:

![image](https://cloud.githubusercontent.com/assets/677704/10560052/d7185a86-74f6-11e5-9465-77b34a20ecf2.png)

It's very amateurishly drawn in paint.net, but you get the idea. The F and the G almost look like fingers and a thumb grabbing the U.

**Comment by una** [comment]
<img width="530" alt="screen shot 2015-10-18 at 1 36 23 pm" src="https://github-cloud.s3.amazonaws.com/assets/1693164/10565724/77d0d3d0-759d-11e5-8bbb-fc8d741e7c6a.png">

**Comment by una** [comment]
<img width="514" alt="screen shot 2015-10-18 at 1 58 08 pm" src="https://github-cloud.s3.amazonaws.com/assets/1693164/10565845/4ee27b56-75a0-11e5-8784-30f30fc32e13.png">

**Comment by daveaglick** [comment]
I'll just leave this right here...

![upforgrabs](https://cloud.githubusercontent.com/assets/1020407/10799760/e5938d9c-7d84-11e5-9a4e-83a54ea0c528.png)

**Comment by daveaglick** [comment]
...and an alternate (I like this one better):

![upforgrabs2](https://cloud.githubusercontent.com/assets/1020407/10804822/f6313b8e-7d9f-11e5-8bd5-5e8f5053edf8.png)

**Comment by shiftkey** [comment]
Finally, finally fixed by #260
