### ISSUE TITLE
Incorrect GitHub Issue Count

### ISSUE THREAD

**Issue by dahlbyk** [up-for-grabs/up-for-grabs.net#567]
https://twitter.com/ziki_cz/status/837867100848848898

> CoreFX shows 50 on badge,but has 538 https://github.com/dotnet/corefx/labels/up%20for%20grabs … bug?

Bug. No pagination. As far as @shiftkey and I can tell, the REST API doesn't expose open count per label, but GraphQL does:

```graphql
{
  repository(owner: "dotnet", name: "corefx") {
    issues(labels: ["up for grabs"], states: [OPEN]) {
      totalCount // open count
    }
    label(name: "up for grabs") {
      issues {
        totalCount // total count...useful?
      }
    }
  }
}
```

But GraphQL (preview) requires authentication. So we need a proxy of some sort. Or in the short-term, we could just show 50+... I assume there's an HTTP header we could check to tell if there's a next page?

**Comment by shiftkey** [comment]
> I assume there's an HTTP header we could check to tell if there's a next page?

It's a hack, but you can get an approximation within +/- a page using [the pagination headers](https://developer.github.com/v3/#pagination). The `last` link will give you the number of pages and the page size.

e.g. `<https://api.github.com/user/repos?page=50&per_page=100>; rel="last"`.

**Comment by aph3rson** [comment]
I believe I've fixed this. As @shiftkey mentioned, the pagination headers mention if content has been paginated. Using some math, we can use the number of pages, as well as the number of items on the last page, to determine the actual issue count.

This has been submitted as PR #604.

**Comment by aph3rson** [comment]
Just to give an update, #604 is still pending review, but I wanted to mention that a move to the Search API might be more prudent, as I mentioned in https://github.com/up-for-grabs/up-for-grabs.net/issues/607#issuecomment-300633183. In short, here's what's leading me to that conclusion:

* The results count is returned by the Search API, and doesn't require math to figure it out  
* Search API has more unauthenticated requests than the Issues API  
* Search API allows us to search entire organizations, multiple labels, counts on a milestone, etc.,  
* Related to above, submitters of projects can have a more granular control over what they want their count to be.

**Comment by shiftkey** [comment]
I'm going to close this out as we don't have plans to use the GraphQL endpoint, but #1276 made an improvement here to show a better approximation (using the `Link` headers which indicate how many pages of results there are).

<img width="259" src="https://user-images.githubusercontent.com/359239/62941891-82070200-bdad-11e9-85ba-f332004eb6af.png">

**Comment by shiftkey** [comment]
> But GraphQL (preview) requires authentication. So we need a proxy of some sort. 

#261 is tracking the general problem about us being rate-limited (because we can only make unauthenticated API calls from the user's browser).
