### ISSUE TITLE
External links load within the same tab.

### ISSUE THREAD

**Issue by ifeanyidavid** [up-for-grabs/up-for-grabs.net#682]
The external links to projects load in the same tab as the site thereby causing a user to leave the site without returning.

I modified the links by adding target="_blank" to allow external pages load in separate tabs.

**Comment by shiftkey** [comment]
@ifeanyidavid that linked commit seems like a good fix, feel free to open a PR against the project so I can pull it in!

**Comment by shiftkey** [comment]
LOL, just saw #683. Nevermind!

**Comment by shiftkey** [comment]
Fixed by #683
