### ISSUE TITLE
Real-time stats for outstanding issues

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#75]
Because it's really hard to tell how many issues are actually outstanding without clicking through.
- likely requires a backend - RIP static site
- what do we do when a site has no outstanding issues?

**Comment by jrusbatch** [comment]
:+1:

**Comment by adamralph** [comment]
Does it really need a back end? Could it not just hit the GitHub API from JS on the client? E.g. async after initial page load, stats lights up as they come in.

No outstanding issues - show 'no oustanding issues'? :wink:

**Comment by akoeplinger** [comment]
Accessing the GitHub API from JS wouldn't be a problem in itself I guess, but they enforce a [rate limit](https://developer.github.com/v3/#rate-limiting) for unauthenticated API requests (60 reqs/h). The API also currently doesn't allow fetching only issue count, instead you always get the whole details as well which makes it a bit impractical for this use case.

**Comment by dahlbyk** [comment]
I'm just going to leave this here...
![nerd-sniped](https://cloud.githubusercontent.com/assets/133987/6102425/d55b49bc-affb-11e4-8f91-f9d539f7a389.gif)

**Comment by adamralph** [comment]
:astonished:
