### ISSUE TITLE
Quick Links for Languages/Popular Tags

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#76]
It should be easy to quickly navigate projects based on common tags.

cc @jrusbatch

**Comment by ChrisMissal** [comment]
How do you see this working @shiftkey? Links to the top __ tags? Links that pre-populate the filter?

I was going to take a stab at this, but found myself guessing too much.

**Comment by shiftkey** [comment]
@ChrisMissal I'm not sure - it was so long ago when I logged this, and past me was vague and unhelpful.

What if we had a short list of the most common tags below the filter box - here's a crude mockup:

<img width="746" alt="screen shot 2015-07-28 at 11 36 43 am" src="https://cloud.githubusercontent.com/assets/359239/8922109/d0ac13fe-351d-11e5-8201-bfb5c7857693.png">

When you click on the tag, the filter gets pre-populated and then the filtering should kick in.

**Comment by ChrisMissal** [comment]
Excellent, this was my initial thought as well.
![selfie-0](http://i.imgur.com/y4O1sYh.gif)

**Comment by mikecole** [comment]
@ChrisMissal that beard.

**Comment by michaelybecker** [comment]
Hi! Looking for up-for-grabs's but this seems wonderfully implemented. Is there a reason this issue isn't closed? (Pardon my n00bness, general disclaimers apply etc.)

**Comment by shiftkey** [comment]
@MichaelHazani nope, no good reason at all! Thanks for reminding me!
