### ISSUE TITLE
Question about tags

### ISSUE THREAD

**Issue by matthew-dean** [up-for-grabs/up-for-grabs.net#782]
Hey, I just recently came across this project. I was curious about surfacing Less on the site as I'm one of the core contributors. First: when I search "less" as a tag, can you tell me why https://github.com/less/less.js itself doesn't appear on that list (or any of the related repos like https://github.com/less/less-docs)?

I've now tagged tasks in both of those as "up-for-grabs", but I'm not sure how you do other project tagging. Can you let me know?

**Comment by ritwik12** [comment]
@matthew-dean "up-for-grabs" is used as Label not tag.
And I am not able to  understand you clearly, for tags- the projects who are tagged with less when they submitted their .yml are tagged with less and you can search them using "less" on the website.


![1](https://user-images.githubusercontent.com/20038775/31981113-a8dbb0fa-b96e-11e7-846f-47be33d02f56.JPG)

you can see that here

**Comment by matthew-dean** [comment]
@ritwik12 Submitted `.yml` to what? You're not just doing Github searches?

**Comment by ritwik12** [comment]
@matthew-dean No, why would I do GitHub search?
You are talking about up-for-grabs.net search right?

**Comment by matthew-dean** [comment]
@ritwik12 Let me rephase: how is that list populated, is that documented, and how may I add to the list?

**Comment by ritwik12** [comment]
@matthew-dean It is mentioned in readme.md
Here have a look.


How This All Works

We use a few great features of Jekyll and GitHub Pages to host this entire site for free.

    We are using a file called scripts.html which is an include file. When we publish the site, Jekyll uses this to concatenate and generate the scripts that will actually be downloaded when a user visits the site.
    Within the scripts.html template, we're referencing site.data.projects, which gives us access to the entire directory of .yml files as a set of variables. We combine this with the jsonify liquid transformer to turn them into a JSON object. This means that the raw data is generated once, so it downloads very quickly as static data.
    When the web page is opened, our startup JS processes each project in the array of projects and pushes it into the array that the rest of the site uses.
    We use travis-ci to run a custom ruby script, cibuild, that checks all the .yml files to make sure they can be appropriately parsed. This makes sure we don't merge any incorrectly formed project files.

What this means is that, when a pull request is merged, GitHub Pages automatically builds the site via Jekyll and publishes it to our GitHub -- no database or hosting needed. (Thanks, GitHub!)

>

**Comment by ritwik12** [comment]
@matthew-dean  It is mentioned in README.md
 Have a look.

 How This All Works

We use a few great features of Jekyll and GitHub Pages to host this entire site for free.

    We are using a file called scripts.html which is an include file. When we publish the site, Jekyll uses this to concatenate and generate the scripts that will actually be downloaded when a user visits the site.
    Within the scripts.html template, we're referencing site.data.projects, which gives us access to the entire directory of .yml files as a set of variables. We combine this with the jsonify liquid transformer to turn them into a JSON object. This means that the raw data is generated once, so it downloads very quickly as static data.
    When the web page is opened, our startup JS processes each project in the array of projects and pushes it into the array that the rest of the site uses.
    We use travis-ci to run a custom ruby script, cibuild, that checks all the .yml files to make sure they can be appropriately parsed. This makes sure we don't merge any incorrectly formed project files.

What this means is that, when a pull request is merged, GitHub Pages automatically builds the site via Jekyll and publishes it to our GitHub -- no database or hosting needed. (Thanks, GitHub!)

**Comment by ritwik12** [comment]
@matthew-dean It is mentioned in README.md 
Have a look.

How This All Works

We use a few great features of Jekyll and GitHub Pages to host this entire site for free.

- We are using a file called scripts.html which is an include file. When we publish the site, Jekyll uses this to concatenate and generate the scripts that will actually be downloaded when a user visits the site.

- Within the scripts.html template, we're referencing site.data.projects, which gives us access to the entire directory of .yml files as a set of variables. We combine this with the jsonify liquid transformer to turn them into a JSON object. This means that the raw data is generated once, so it downloads very quickly as static data.
- When the web page is opened, our startup JS processes each project in the array of projects and pushes it into the array that the rest of the site uses.
- We use travis-ci to run a custom ruby script, cibuild, that checks all the .yml files to make sure they can be appropriately parsed. This makes sure we don't merge any incorrectly formed project files.

What this means is that, when a pull request is merged, GitHub Pages automatically builds the site via Jekyll and publishes it to our GitHub -- no database or hosting needed. (Thanks, GitHub!)

**Comment by ritwik12** [comment]
@matthew-dean Please go through this https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/README.md

**Comment by ritwik12** [comment]
@matthew-dean Is it resolved?

**Comment by ritwik12** [comment]
@matthew-dean I think this issue can be closed now.
