### ISSUE TITLE
Pending PRs

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#784]
Sorry for this issue, but I am noticing that a lot of pull requests are pending for a long time and they are not even reviewed yet.
Please review the PRs and make up-for-grabs.net repo active as it was.

**Comment by shiftkey** [comment]
@ritwik12 thanks for your concern, but I'm working through these whenever I have spare time. I'm currently travelling and presenting this week and next week, and trying to keep on top of my regular work while not burning myself out (again).

**Comment by ritwik12** [comment]
@shiftkey I know that you are working whenever you can, what I mean is that only you are reviewing. No one else is active.I think the problem is that it's a project maintained by a single person that is you. if that is the case then it is totally fine if PRs are getting delayed.

**Comment by dahlbyk** [comment]
@ritwik12 are you volunteering to help with review and triage?

**Comment by ritwik12** [comment]
@ritwik12 yes I would be happy to help as much as I can on the basis of my current knowledge.

**Comment by dahlbyk** [comment]
Welcome to the team! Let us know if you have any questions.

**Comment by ritwik12** [comment]
Thanks a lot, @dahlbyk , I will do my best.
