### ISSUE TITLE
Food for thought

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#91]
The food has been discontinued

**Comment by akoeplinger** [comment]
That page 404s for me, or am I missing something?

**Comment by shiftkey** [comment]
Yeah, I'm afraid it does. My apologies.

It was more for the core team, but if you can find me on the internets I'm happy to tell you more.

**Comment by akoeplinger** [comment]
No worries, I was just curious. Mail sent :smile:

**Comment by akoeplinger** [comment]
Lol, just stumbled over this again while looking at the repo, I still wonder what's it about?

**Comment by shiftkey** [comment]
Sadly it's on the backburner for now. Nevermind.
