### ISSUE TITLE
Include a CONTRIBUTING.md

### ISSUE THREAD

**Issue by ghost** [up-for-grabs/up-for-grabs.net#911]
Perhaps it would be good to write up a CONTRIBUTING.md to help new contributors, especially given that this website's aim is to help new developers find projects to make contributions to. 

[Here](https://gist.github.com/PurpleBooth/b24679402957c63ec426) is a nice template to help with writing this up. I would gladly take this on as my first PR if you would like.

**Comment by shiftkey** [comment]
Closing as the account interested in contributing no longer exists, and the [Add a project](https://github.com/up-for-grabs/up-for-grabs.net#add-a-project) link is prominent enough in the README to do in the interim.

But if someone wants to take a shot at a `CONTRIBUTING.md` doc they're welcome to just submit the PR.
