### ISSUE TITLE
site.github.url creating a mixed content error 

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#923]
Reopening issue [#238](https://github.com/github/pages-gem/issues/238#issuecomment-385857100) as suggested by @dahlbyk  in #921.

Problem - site.github.url`metadata provides http url creating a mixed content error when used on github.io pages.

Solution - making {{ site.github.url }} resolve with https if the request came over https.

**Comment by dahlbyk** [comment]
We can close this by reverting adee0219411f151d3a16257a6639b7536e9ac2b5 once https://github.com/github/pages-gem/issues/238 or equivalent has been fixed.

**Comment by shiftkey** [comment]
From https://github.com/github/pages-gem/issues/238#issuecomment-386470334 a few hours ago:

> When you click the "Enforce HTTPS" button, your `site.github.url` should contain `https://`.

@dahlbyk this has been enabled on our side, so I guess we're just stuck doing a YOLO-deploy with reverting that commit?

**Comment by dahlbyk** [comment]
Confirmed; view source shows `https://up-for-grabs.net` now instead of `//up-for-grabs.net`.

**Comment by ritwik12** [comment]
I also saw that, It is working with https://

**Comment by ritwik12** [comment]
So what's left now?

**Comment by dahlbyk** [comment]
> So what's left now?

Nothing 😀

**Comment by ritwik12** [comment]
@dahlbyk :)
