### ISSUE TITLE
Remove Beavy from list of projects

### ISSUE THREAD

**Issue by ramlaxman** [up-for-grabs/up-for-grabs.net#939]
[Beavy Website](http://www.beavy.xyz/)  is closed.
**Github status:** Project is inactive from last 3 years.
**Reason:** It is quite demotivating for new contributors to initiate pull request and not getting accepted for new project.

**Comment by shiftkey** [comment]
@ramlaxman feel free to submit a PR to remove the file

**Comment by ramlaxman** [comment]
Please check [this PR](https://github.com/up-for-grabs/up-for-grabs.net/pull/941)
